In [5]:
import pandas as pd
print("done")

done

In [8]:
name = [ "lathika","tha","thww"]
n= pd.Series(name)
n

0    lathika
1        tha
2       thww
dtype: str

In [11]:
n1 = pd.Series(["lathika","tha","thww"],index=["name1","name2","name3"])
n1

name1    lathika
name2        tha
name3       thww
dtype: str

In [15]:
name1 = ["lathika","tha","thww"]
n2=pd.Series(name1,index=range(1,4))
n2

1    lathika
2        tha
3       thww
dtype: str

In [17]:
bao= {"name": "Ran", "Age":33}

s=pd.Series(bao,index= [1,2])
s

1    NaN
2    NaN
dtype: object

In [20]:
bio= {"name": "Ran", "Age":33}

s=pd.DataFrame(bio,index=[1])
s

  name  Age
1  Ran   33

In [21]:
bio  = {"Name": ["Ram","jahs","insa"],"Age":[22,22,22]}
a = pd.DataFrame(bio)

In [22]:
bio

{'Name': ['Ram', 'jahs', 'insa'], 'Age': [22, 22, 22]}

In [23]:
a

   Name  Age
0   Ram   22
1  jahs   22
2  insa   22

In [28]:
a["Age"]

0    22
1    22
2    22
Name: Age, dtype: int64

In [30]:
a.head(1)

  Name  Age
0  Ram   22

In [32]:
a.tail(1)

   Name  Age
2  insa   22

In [33]:
print(a.to_string())

   Name  Age
0   Ram   22
1  jahs   22
2  insa   22