## Pandas

+ Python
+ Numpy
    + DA
    + DS
    + AI/ML

+ Pands --> Panal Data 
    + series
        + 1D -array
    + Data frames
        + multiple data
 + Series/data frame --> store,maniplate,import,export,diaplay

In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.3

In [3]:
age=[22,25,65,34,55]

In [4]:
series=pd.Series(age)
print(series)

0    22
1    25
2    65
3    34
4    55
dtype: int64

In [5]:
print(series.loc[1]) # index and we can create your own index

25

In [7]:
series=pd.Series(age,index=["lathika","vinoth","kumar","siva","mani"])
print(series)

lathika    22
vinoth     25
kumar      65
siva       34
mani       55
dtype: int64

In [9]:
print(series.loc["lathika"])

22

In [10]:
print(series.iloc[1]) # index

25

In [11]:
age ={
    "lathika" :23,
    "mani" :33,
    "sobana":22,
    "kumar":33
}

In [13]:
series=pd.Series(age)
print(series)

lathika    23
mani       33
sobana     22
kumar      33
dtype: int64

In [15]:
# we also do filtering

print(series[series>30])
print(series[series<30])

mani     33
kumar    33
dtype: int64
lathika    23
sobana     22
dtype: int64

In [2]:
students ={
    "Name " : ["lathika","karthi","kali"],
    "Age": [22,24,25],
    "sub":["DA","DE","genai"]
}

In [3]:
df=pd.DataFrame(students)

In [4]:
print(df)

     Name   Age    sub
0  lathika   22     DA
1   karthi   24     DE
2     kali   25  genai

In [5]:
df = pd.DataFrame(students,index=[1,2,3])
print(df)

     Name   Age    sub
1  lathika   22     DA
2   karthi   24     DE
3     kali   25  genai

In [6]:
print(df.loc[1])

Name     lathika
Age           22
sub           DA
Name: 1, dtype: object

In [8]:
print(df.iloc[1])

Name     karthi
Age          24
sub          DE
Name: 2, dtype: object

In [9]:
df["phone"]=[1231223,241323,3241341]

In [10]:
print(df)

     Name   Age    sub    phone
1  lathika   22     DA  1231223
2   karthi   24     DE   241323
3     kali   25  genai  3241341

In [11]:
print(students)

{'Name ': ['lathika', 'karthi', 'kali'], 'Age': [22, 24, 25], 'sub': ['DA', 'DE', 'genai']}

In [12]:
s4 = pd.DataFrame({"Name ":"sobana","age":22,"sub":"DS"},index=[4])

In [14]:
df=pd.concat([df,s4])
print(df)

     Name    Age    sub      phone   age
1  lathika  22.0     DA  1231223.0   NaN
2   karthi  24.0     DE   241323.0   NaN
3     kali  25.0  genai  3241341.0   NaN
4   sobana   NaN     DS        NaN  22.0

In [15]:
students = pd.DataFrame([
    {"Name ":"sobi","Age":22,"sub":"DS"},
    {"Name":"ragi","Age":26,"sub":"QA"}
]
                        ,index=[5,4])

In [16]:
df = pd.concat([df,students])
print(df)

     Name    Age    sub      phone   age  Name
1  lathika  22.0     DA  1231223.0   NaN   NaN
2   karthi  24.0     DE   241323.0   NaN   NaN
3     kali  25.0  genai  3241341.0   NaN   NaN
4   sobana   NaN     DS        NaN  22.0   NaN
5     sobi  22.0     DS        NaN   NaN   NaN
4      NaN  26.0     QA        NaN   NaN  ragi

In [31]:
d =df.loc[(df['Age']>20) | (df["Age"]<25)]
print(d)

     Name    Age    sub      phone  age  Name
1  lathika  22.0     DA  1231223.0  NaN   NaN
2   karthi  24.0     DE   241323.0  NaN   NaN
3     kali  25.0  genai  3241341.0  NaN   NaN
5     sobi  22.0     DS        NaN  NaN   NaN
4      NaN  26.0     QA        NaN  NaN  ragi

In [36]:
d =df.loc[(df["Name"].str.startswith("k")) ]
print(d)

Empty DataFrame
Columns: [Name , Age, sub, phone, age, Name]
Index: []

In [39]:
print(df["Name"].to_list())

[nan, nan, nan, nan, nan, 'ragi']

In [11]:
d = pd.read_csv("C:\\Users\\Admin\\OneDrive\\Documents\\CourseNotes\\Data.csv")

In [12]:
print(d.head(2))

    id    name  age department  salary
0  101    Ravi   25         IT   35000
1  102  Anitha   28         HR   40000

In [13]:
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          4 non-null      int64
 1   name        4 non-null      str
 2   age         4 non-null      int64
 3   department  4 non-null      str
 4   salary      4 non-null      int64
dtypes: int64(3), str(2)
memory usage: 292.0 bytes

In [5]:
d.describe()

               id        age        salary
count    4.000000   4.000000      4.000000
mean   102.500000  27.250000  39500.000000
std      1.290994   2.217356   4203.173404
min    101.000000  25.000000  35000.000000
25%    101.750000  25.750000  37250.000000
50%    102.500000  27.000000  39000.000000
75%    103.250000  28.500000  41250.000000
max    104.000000  30.000000  45000.000000

In [15]:
d.to_string() # all rows print

'    id    name  age department  salary\n0  101    Ravi   25         IT   35000\n1  102  Anitha   28         HR   40000\n2  103   Kumar   30    Finance   45000\n3  104   Divya   26         IT   38000'

In [8]:
print(d["id"].to_string())

0    101
1    102
2    103
3    104

In [9]:
print(d[["id","name"]].to_string())

    id    name
0  101    Ravi
1  102  Anitha
2  103   Kumar
3  104   Divya

In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("C:\\Users\\Admin\\OneDrive\\Documents\\CourseNotes\\employee_data_cleaning_practice_200_rows.csv")

In [4]:
print(data)

    Employee_ID Employee_Name   Age  Gender         Department        City  \
0             1   Sneha Kumar  38.0  Female            finance   Bangalore
1             2   Arun Sharma  34.0       F            finance     Chennai
2             3    Anitha Rao  17.0    male         Operations     chennai
3             4  Sneha Sharma  45.0    Male          Marketing     Chennai
4             5     Sneha Das  26.0       F         Operations     Chennai
..          ...           ...   ...     ...                ...         ...
195         196     Kavya Rao  51.0    Male          Marketing       Delhi
196         197   Nisha Kumar  32.0       M   Human Resources      chennai
197         198     Arun Iyer   0.0     NaN   Human Resources         Pune
198         199  Suresh Reddy  28.0       M          Marketing  BANGALORE
199         200   Gokul Reddy  32.0  female            finance     chennai

                           Email Employment_Type  Salary Joining_Date  \
0         sneha.kumar1@gmail.com       Part time   53000   2020-07-03
1       arun.sharma2@company.com        contract   53000   2023-09-01
2          anitha.rao3@gmail.com       Part-Time   58000   2018-01-27
3        sneha.sharma4@yahoo.com        contract   33000   2022-01-10
4         sneha.das5@company.com        contract  103000   2021-04-15
..                           ...             ...     ...          ...
195       kavya.rao196@yahoo.com             NaN  118000   2020-03-27
196     nisha.kumar197@gmail.com        contract   83000   2019-12-22
197       arun.iyer198@yahoo.com       Part-Time  113000   2019-03-16
198  suresh.reddy199@company.com       Full-Time   68000   2019-10-28
199     gokul.reddy200@yahoo.com       Full-Time  113000   2025-03-01

     Performance_Score  Attendance_Percentage
0                  NaN                   75.0
1                  6.0                    NaN
2                  4.0                  100.0
3                  0.0                   -5.0
4                  2.0                   75.0
..                 ...                    ...
195                2.0                   90.0
196                5.0                   75.0
197                6.0                  105.0
198                3.5                   95.0
199                NaN                   80.0

[200 rows x 12 columns]

In [16]:
print(data.to_string())

    Employee_ID    Employee_Name   Age  Gender         Department        City                         Email Employment_Type     Salary Joining_Date  Performance_Score  Attendance_Percentage
0             1      Sneha Kumar  38.0  Female            finance   Bangalore        sneha.kumar1@gmail.com       Part time      53000   2020-07-03                NaN                   75.0
1             2      Arun Sharma  34.0       F            finance     Chennai      arun.sharma2@company.com        contract      53000   2023-09-01                6.0                    NaN
2             3       Anitha Rao  17.0    male         Operations     chennai         anitha.rao3@gmail.com       Part-Time      58000   2018-01-27                4.0                  100.0
3             4     Sneha Sharma  45.0    Male          Marketing     Chennai       sneha.sharma4@yahoo.com        contract      33000   2022-01-10                0.0                   -5.0
4             5        Sneha Das  26.0       F         Operations     Chennai        sneha.das5@company.com        contract     103000   2021-04-15                2.0                   75.0
5             6      Anitha Iyer  26.0  female   Human Resources         Pune        anitha.iyer6@yahoo.com       Part-Time      53000   2019-02-18                3.5                  100.0
6             7       Vijay Iyer  25.0       M              Sales    Hyderbad         vijay.iyer7@gmail.com       full time     113000   2025-02-13                NaN                   95.0
7             8      Nisha Reddy  41.0    male                 it       Delhi        nisha.reddy8@gmail.com       Full-Time      23000   2020-07-27                4.0                  100.0
8             9        Vijay Rao  46.0       F            Finance        Pune          vijay.rao9@gmail.com        contract     118000   2023-02-23                6.0                   -5.0
9            10    Suresh Joseph  48.0     NaN            Finance      Mumbai     suresh.joseph10@yahoo.com       Full-Time     108000   2022-06-24                1.0                   80.0
10           11    Karthik Patel  48.0     NaN              SALES     chennai     karthik.patel11@yahoo.com       Part time     113000   2018-09-18                5.0                   -5.0
11           12      Arun Sharma  55.0   Male           Marketing   Bangalore       arun.sharma12@yahoo.com       Part-Time      58000   2025-03-10                0.0                   75.0
12           13      Suresh Nair  32.0       F            finance        Pune     suresh.nair13@company.com       Part-Time      98000   2019-03-12                3.5                   85.0
13           14       Nisha Nair  21.0  female                 HR     Chennai        nisha.nair14@yahoo.com             NaN     113000   2021-08-20                5.0                   90.0
14           15      Priya Reddy   0.0       M                 HR  BANGALORE      priya.reddy15@company.com       Part-Time      28000   2018-12-17                0.0                   -5.0
15           16       Divya Iyer  54.0    male              Sales    Hyderbad        divya.iyer16@gmail.com       full time     113000   2022-09-30                3.5                  105.0
16           17        hari rao   28.0       F                 IT       Delhi          hari.rao17@gmail.com       Part time      53000   2020-07-09                4.0                   75.0
17           18      Rahul Kumar  35.0       F            finance   Bangalore       rahul.kumar18@yahoo.com        Contract      28000   2018-05-09                0.0                   90.0
18           19      Nisha Patel   NaN       F                 it  BANGALORE        nisha.patel19@gmail.com       Full-Time     108000   2023-04-21                2.0                    NaN
19           20        Pooja Das  47.0   Male                  IT   Bangalore         pooja.das20@gmail.com        contract      88000   2026-03-06                3.5                   80.0
20           21     Anitha Reddy  33.0    male            Finance     chennai      anitha.reddy21@gmail.com       full time     103000   2023-01-12                4.0                   80.0
21           22       Manoj Nair  27.0       F                 HR     Chennai      manoj.nair22@company.com       Part-Time      23000   2025-04-25                NaN                  105.0
22           23      Deepa Reddy  46.0    male                 it     Chennai      deepa.reddy23 @yahoo.com             NaN      23000   2019-11-06                0.0                   95.0
23           24       Kavya Nair  52.0    Male                 IT      Mumbai        kavya.nair24@yahoo.com        contract      38000   2020-02-17                3.5                   75.0
24           25     Priya Joseph  51.0  Female            finance     Chennai      priya.joseph25@gmail.com             NaN      98000   2023-12-16                3.0                   80.0
25           26    Swetha Sharma  36.0    Male              SALES      Mumbai   swetha.sharma26@company.com       Part time      78000   2019-05-07                2.0                    NaN
26         E027     Gokul Joseph  54.0    male              Sales       Delhi      gokul.joseph27@gmail.com       full time      68000   2020-12-04                3.0                   95.0
27           28      Manoj Singh  25.0  Female                 HR     Chennai     manoj.singh28@company.com       Part time      18000   2023-02-21                4.0                   -5.0
28           29     Suresh Patel  43.0     NaN            Finance        Pune                 invalid-email             NaN      28000   2020-09-27                6.0                   95.0
29           30      Swetha Nair  21.0    male            Finance   Bangalore       swetha.nair30@yahoo.com       Full-Time        NaN   2024-03-21                2.0                   -5.0
30           31     Karthik Iyer  39.0    male              Sales       Delhi    karthik.iyer31@company.com       Part time  45000 INR   2020-05-12                0.0                   95.0
31           32     Priya Sharma  48.0    male            Finance       Delhi      priya.sharma32@gmail.com       Part-Time      58000   2018-06-30                0.0                   -5.0
32           33       Kavya Nair  21.0    Male            finance   Hyderabad      kavya.nair33@company.com             NaN      33000   2018-11-05                3.5                   -5.0
33           34     karthik das   29.0       F         Operations     Chennai       karthik.das34@yahoo.com        contract      23000   2021-06-16                4.0                   80.0
34           35       Pooja Nair  47.0       M            Finance      Mumbai        pooja.nair35@gmail.com       full time     113000   2026-05-28                1.0                   85.0
35           36         Ravi Das  36.0    Male                 it   Bangalore        ravi.das36@company.com             NaN      58000   2019-10-15                0.0                   90.0
36           37        Vijay Rao  43.0   Male               Sales     Chennai         vijay.rao37@gmail.com        Contract      63000   21/07/2020                5.0                   80.0
37           38     Suresh Singh   NaN  Female                 IT       Delhi    suresh.singh38@company.com        Contract      78000   2025-08-15                3.0                   95.0
38           39     Priya Sharma  65.0  Female                 it       Delhi    priya.sharma39@company.com       full time      83000   2021-11-16                4.0                   95.0
39           40        Priya Das  21.0   Male          Operations      Mumbai       priya.das40@company.com       Full-Time      98000   2024-01-15                3.5                  100.0
40           41       Sneha Iyer  53.0    male                 it       Delhi        sneha.iyer41@yahoo.com       Part time      63000   06-24-2025                3.0                   90.0
41           42        Kavya Das  32.0    Male            finance     chennai         kavya.das42@yahoo.com        Contract     113000   2024-05-20                5.0                   90.0
42           43     Kavya Joseph  65.0     NaN   Human Resources     Chennai       kavya.joseph43@yahoo.com        contract     118000   2021-08-12                4.0                   -5.0
43           44      Deepa Patel  26.0  Female         Operations     Chennai     deepa.patel44@company.com             NaN      63000   2023-10-13                4.0                   95.0
44           45     Anitha Reddy  30.0  Female              SALES  BANGALORE       anitha.reddy45@gmail.com       full time      18000   2018-07-09                NaN                   90.0
45           46         Ajay Rao  46.0   Male                  HR     Chennai       ajay.rao46 @company.com       Part-Time      53000   2019-08-28                3.0                   -5.0
46           47      Manoj Kumar   NaN  female   Human Resources    Hyderabad       manoj.kumar47@yahoo.com             NaN      53000          NaN                0.0                   -5.0
47           48       Kavya Nair  49.0       F          Marketing  BANGALORE         kavya.nair48@yahoo.com             NaN      43000   2026-05-05                5.0                   -5.0
48           49      Deepa Reddy  38.0    male              Sales        Pune     deepa.reddy49@company.com        Contract      88000   2018-11-14                3.5                   -5.0
49           50      Rahul Patel  30.0  Female              Sales   Hyderabad     rahul.patel50@company.com       full time      53000   2022-04-18                NaN                  100.0
50           51       nisha rao   47.0    Male              SALES     chennai         nisha.rao51@yahoo.com             NaN      23000   2020-04-27                NaN                  105.0
51           52       Arun Singh  40.0       F              SALES    Hyderbad      arun.singh52@company.com       full time      78000   2022-09-13                4.0                   95.0
52           53        Kavya Rao  22.0       M                NaN     chennai       kavya.rao53@company.com             NaN      78000   2021-10-08                0.0                   85.0
53         E054      Swetha Nair  22.0   Male                  HR     Chennai     swetha.nair54@company.com       Part-Time      78000   2024-08-21                0.0                   85.0
54           55       Priya Iyer  45.0   Male          Operations       Delhi        priya.iyer55@yahoo.com        Contract      68000   2020-05-16                NaN                   95.0
55           56        Rahul Rao  22.0  Female              Sales       Delhi         rahul.rao56@gmail.com             NaN          0   2024-01-19                1.0                   75.0
56           57     Anitha Reddy   NaN  Female   Human Resources    Hyderabad      anitha.reddy57@gmail.com       Part time     113000   2019-09-17                4.0                  105.0
57           58     Suresh Singh  31.0    male            Finance   Bangalore                 invalid-email       Full-Time     113000   2024-10-23                1.0                   95.0
58           59        Gokul Das  46.0  Female              Sales     Chennai         gokul.das59@gmail.com        contract     -25000   2020-03-23                5.0                   80.0
59           60      Gokul Kumar  43.0  female                 HR       Delhi     gokul.kumar60@company.com       Full-Time     103000   2022-10-21                NaN                  105.0
60           61        Sneha Das  44.0       M                 it   Hyderabad       sneha.das61@company.com        contract     118000   2023-02-27                6.0                   95.0
61           62      Swetha Nair  51.0  female          Marketing     Chennai     swetha.nair62@company.com             NaN  45000 INR   2022-11-20                4.0                   80.0
62           63       Suresh Rao  36.0    Male         Operations     chennai      suresh.rao63@company.com       full time      88000   2024-05-23                3.5                   85.0
63           64      Deepa Reddy  43.0    Male          Marketing     Chennai       deepa.reddy64@yahoo.com       Part time      58000   2021-10-26                4.0                   80.0
64           65       Anitha Das  52.0     NaN   Human Resources   BANGALORE       anitha.das65@company.com             NaN     103000   2020-09-11                1.0                   80.0
65           66      Meena Reddy  46.0     NaN         Operations     Chennai       meena.reddy66@yahoo.com       Part time     -25000   2020-09-23                6.0                  100.0
66           67       Kavya Nair  42.0    male          Marketing        Pune        kavya.nair67@yahoo.com       Part-Time      73000   2025-11-18                2.0                   90.0
67           68     ravi sharma   55.0    male   Human Resources       Mumbai       ravi.sharma68@gmail.com        contract     -25000   2020-01-29                6.0                   95.0
68           69      Sneha Reddy  39.0       M                 IT        Pune      sneha.reddy69 @gmail.com        Contract      53000   2022-01-18                1.0                   75.0
69           70       Nisha Iyer  29.0    male                 IT   Bangalore        nisha.iyer70@yahoo.com       full time     118000   2026-06-11                0.0                  105.0
70           71       Ravi Patel  24.0     NaN                 it   Bangalore        ravi.patel71@gmail.com       Full-Time      58000   2023-05-11                1.0                   85.0
71           72   Karthik Joseph  40.0       F                 it    Hyderbad    karthik.joseph72@gmail.com             NaN      28000   2020-10-13                6.0                    NaN
72           73        Manoj Rao  40.0    Male              SALES     Chennai         manoj.rao73@yahoo.com       Part time     108000   2022-10-23                2.0                   90.0
73           74       Vijay Iyer  26.0       M                 HR    Hyderbad        vijay.iyer74@gmail.com       Full-Time      43000   09/09/2020                NaN                  105.0
74           75       Swetha Rao  39.0  Female   Human Resources         Pune        swetha.rao75@yahoo.com        contract      23000   2020-08-06                4.0                   95.0
75           76      Gokul Reddy   NaN       M          Marketing   Hyderabad       gokul.reddy76@gmail.com       Full-Time      33000   2024-02-09                1.0                   85.0
76           77     Meena Joseph   0.0   Male           Marketing  BANGALORE       meena.joseph77@gmail.com        Contract      63000   2022-12-04                6.0                   -5.0
77           78        Deepa Rao  26.0    male              SALES       Delhi         deepa.rao78@yahoo.com       Full-Time     113000   2018-06-13                2.0                   90.0
78           79     Gokul Joseph  22.0     NaN            Finance     Chennai    gokul.joseph79@company.com       Part time        NaN   2021-01-08                0.0                   95.0
79           80     Divya Joseph  48.0   Male          Operations  BANGALORE       divya.joseph80@gmail.com        Contract     118000   2023-07-08                3.5                   80.0
80         E081      Divya Singh  47.0    Male            finance     chennai       divya.singh81@yahoo.com       full time     -25000   2023-07-23                2.0                  100.0
81           82     Suresh Singh  28.0   Male    Human Resources     Hyderbad      suresh.singh82@gmail.com       Full-Time      78000   10-09-2023                4.0                   -5.0
82           83     Pooja Joseph  52.0       M          Marketing      Mumbai      pooja.joseph83@gmail.com        Contract     118000   2022-12-16                0.0                  105.0
83           84      Sneha Kumar  65.0    Male            finance        Pune       sneha.kumar84@gmail.com       Part time      53000   2025-12-17                NaN                   80.0
84           85   anitha sharma   50.0    male          Marketing  BANGALORE      anitha.sharma85@gmail.com       full time      33000   2025-04-07                0.0                  105.0
85           86       Anitha Rao   NaN       M              SALES    Chennai         anitha.rao86@gmail.com             NaN      38000   2022-04-21                2.0                   95.0
86           87      Kavya Singh  53.0     NaN              SALES        Pune                 invalid-email             NaN      58000   2018-01-11                3.0                  105.0
87           88        Nisha Rao  43.0  female   Human Resources      chennai       nisha.rao88@company.com             NaN      68000   2024-03-10                4.0                   90.0
88           89        Gokul Das  35.0   Male                  it  BANGALORE          gokul.das89@yahoo.com        contract      83000   2018-06-28                3.0                  105.0
89           90      Priya Patel  53.0     NaN                 HR  BANGALORE        priya.patel90@gmail.com       Full-Time     108000   2021-09-21                3.0                    NaN
90           91   Karthik Sharma  51.0  female                 HR     chennai  karthik.sharma91@company.com             NaN      58000   2021-10-18                6.0                    NaN
91           92         Ravi Rao  55.0       F          Marketing      Mumbai         ravi.rao92 @gmail.com        contract      23000   2024-12-04                2.0                    NaN
92           93     Sneha Sharma  49.0  female                 IT     Chennai      sneha.sharma93@yahoo.com             NaN  45000 INR   2025-10-13                1.0                   95.0
93           94      Pooja Singh  48.0       M              SALES     chennai     pooja.singh94@company.com       Part-Time      38000          NaN                3.0                   80.0
94           95       Swetha Das   NaN    male   Human Resources       Mumbai        swetha.das95@gmail.com       full time      93000   2024-07-16                5.0                   75.0
95           96       Manoj Iyer  55.0    male              SALES       Delhi        manoj.iyer96@yahoo.com        contract      43000   2018-10-30                NaN                   95.0
96           97       Manoj Iyer  33.0  female                 it      Mumbai        manoj.iyer97@gmail.com       Part time      78000   2023-06-03                5.0                   95.0
97           98         Arun Das  38.0     NaN              SALES     Chennai        arun.das98@company.com             NaN      18000   2024-05-07                5.0                   90.0
98           99     Swetha Singh  35.0  Female            Finance        Pune    swetha.singh99@company.com        contract     118000   2020-02-18                1.0                   95.0
99          100      Manoj Kumar  17.0  female          Marketing   Bangalore      manoj.kumar100@gmail.com        contract      73000   2026-03-19                NaN                   85.0
100         101      Vijay Patel  55.0    male            Finance        Pune    vijay.patel101@company.com             NaN      73000   2023-12-15                0.0                   95.0
101         102     ravi sharma   50.0  female            finance     chennai      ravi.sharma102@gmail.com       Full-Time      28000   2019-07-31                NaN                   75.0
102         103      Suresh Nair  28.0   Male               SALES        Pune    suresh.nair103@company.com             NaN      88000   2022-02-18                3.5                   80.0
103         104       Anitha Rao  22.0  Female              Sales     Chennai       anitha.rao104@yahoo.com        contract     113000   2024-04-18                0.0                   95.0

In [6]:
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            200 non-null    str
 1   Employee_Name          200 non-null    str
 2   Age                    182 non-null    float64
 3   Gender                 177 non-null    str
 4   Department             197 non-null    str
 5   City                   200 non-null    str
 6   Email                  200 non-null    str
 7   Employment_Type        164 non-null    str
 8   Salary                 193 non-null    str
 9   Joining_Date           196 non-null    str
 10  Performance_Score      180 non-null    float64
 11  Attendance_Percentage  180 non-null    float64
dtypes: float64(3), str(9)
memory usage: 18.9 KB
None

In [9]:
data.describe()

              Age  Performance_Score  Attendance_Percentage
count  182.000000         180.000000             180.000000
mean    38.137363           3.150000              77.333333
std     12.475294           1.962569              35.138990
min      0.000000           0.000000              -5.000000
25%     29.000000           2.000000              80.000000
50%     40.000000           3.500000              90.000000
75%     48.000000           5.000000             100.000000
max     65.000000           6.000000             105.000000

In [8]:
data.head()

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,2020-07-03,NaN,75.0
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,2023-09-01,6.0,NaN
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,2018-01-27,4.0,100.0
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,2022-01-10,0.0,-5.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,2021-04-15,2.0,75.0

In [18]:
print(data["Age"].to_string()) # column only

0      38.0
1      34.0
2      17.0
3      45.0
4      26.0
5      26.0
6      25.0
7      41.0
8      46.0
9      48.0
10     48.0
11     55.0
12     32.0
13     21.0
14      0.0
15     54.0
16     28.0
17     35.0
18      NaN
19     47.0
20     33.0
21     27.0
22     46.0
23     52.0
24     51.0
25     36.0
26     54.0
27     25.0
28     43.0
29     21.0
30     39.0
31     48.0
32     21.0
33     29.0
34     47.0
35     36.0
36     43.0
37      NaN
38     65.0
39     21.0
40     53.0
41     32.0
42     65.0
43     26.0
44     30.0
45     46.0
46      NaN
47     49.0
48     38.0
49     30.0
50     47.0
51     40.0
52     22.0
53     22.0
54     45.0
55     22.0
56      NaN
57     31.0
58     46.0
59     43.0
60     44.0
61     51.0
62     36.0
63     43.0
64     52.0
65     46.0
66     42.0
67     55.0
68     39.0
69     29.0
70     24.0
71     40.0
72     40.0
73     26.0
74     39.0
75      NaN
76      0.0
77     26.0
78     22.0
79     48.0
80     47.0
81     28.0
82     52.0
83     65.0
84     50.0
85      NaN
86     53.0
87     43.0
88     35.0
89     53.0
90     51.0
91     55.0
92     49.0
93     48.0
94      NaN
95     55.0
96     33.0
97     38.0
98     35.0
99     17.0
100    55.0
101    50.0
102    28.0
103    22.0
104    29.0
105    44.0
106    47.0
107    55.0
108    22.0
109    35.0
110    22.0
111    47.0
112    49.0
113     NaN
114    17.0
115     NaN
116    41.0
117    26.0
118    47.0
119    51.0
120     NaN
121    32.0
122    45.0
123    31.0
124    47.0
125    23.0
126    41.0
127    43.0
128     0.0
129    50.0
130    40.0
131    43.0
132     NaN
133    25.0
134    49.0
135     NaN
136    49.0
137    54.0
138    42.0
139    30.0
140    54.0
141    42.0
142    23.0
143    49.0
144    40.0
145    47.0
146    54.0
147    49.0
148    22.0
149    49.0
150    48.0
151     NaN
152    43.0
153     NaN
154    36.0
155    32.0
156    23.0
157    33.0
158    45.0
159    26.0
160    49.0
161    38.0
162    25.0
163    49.0
164    32.0
165    39.0
166    43.0
167    35.0
168    29.0
169    29.0
170     NaN
171    39.0
172    31.0
173     0.0
174    36.0
175    34.0
176    27.0
177    45.0
178    52.0
179    39.0
180    44.0
181    53.0
182     NaN
183    42.0
184    40.0
185    42.0
186    35.0
187    33.0
188    51.0
189     NaN
190    38.0
191     NaN
192    39.0
193    38.0
194    27.0
195    51.0
196    32.0
197     0.0
198    28.0
199    32.0

In [19]:
print(data[["Age","Gender"]].to_string())

      Age  Gender
0    38.0  Female
1    34.0       F
2    17.0    male
3    45.0    Male
4    26.0       F
5    26.0  female
6    25.0       M
7    41.0    male
8    46.0       F
9    48.0     NaN
10   48.0     NaN
11   55.0   Male
12   32.0       F
13   21.0  female
14    0.0       M
15   54.0    male
16   28.0       F
17   35.0       F
18    NaN       F
19   47.0   Male
20   33.0    male
21   27.0       F
22   46.0    male
23   52.0    Male
24   51.0  Female
25   36.0    Male
26   54.0    male
27   25.0  Female
28   43.0     NaN
29   21.0    male
30   39.0    male
31   48.0    male
32   21.0    Male
33   29.0       F
34   47.0       M
35   36.0    Male
36   43.0   Male
37    NaN  Female
38   65.0  Female
39   21.0   Male
40   53.0    male
41   32.0    Male
42   65.0     NaN
43   26.0  Female
44   30.0  Female
45   46.0   Male
46    NaN  female
47   49.0       F
48   38.0    male
49   30.0  Female
50   47.0    Male
51   40.0       F
52   22.0       M
53   22.0   Male
54   45.0   Male
55   22.0  Female
56    NaN  Female
57   31.0    male
58   46.0  Female
59   43.0  female
60   44.0       M
61   51.0  female
62   36.0    Male
63   43.0    Male
64   52.0     NaN
65   46.0     NaN
66   42.0    male
67   55.0    male
68   39.0       M
69   29.0    male
70   24.0     NaN
71   40.0       F
72   40.0    Male
73   26.0       M
74   39.0  Female
75    NaN       M
76    0.0   Male
77   26.0    male
78   22.0     NaN
79   48.0   Male
80   47.0    Male
81   28.0   Male
82   52.0       M
83   65.0    Male
84   50.0    male
85    NaN       M
86   53.0     NaN
87   43.0  female
88   35.0   Male
89   53.0     NaN
90   51.0  female
91   55.0       F
92   49.0  female
93   48.0       M
94    NaN    male
95   55.0    male
96   33.0  female
97   38.0     NaN
98   35.0  Female
99   17.0  female
100  55.0    male
101  50.0  female
102  28.0   Male
103  22.0  Female
104  29.0  Female
105  44.0   Male
106  47.0     NaN
107  55.0       F
108  22.0       F
109  35.0       M
110  22.0  female
111  47.0     NaN
112  49.0    male
113   NaN  Female
114  17.0    male
115   NaN   Male
116  41.0       M
117  26.0    Male
118  47.0    male
119  51.0  Female
120   NaN       M
121  32.0       M
122  45.0    male
123  31.0     NaN
124  47.0   Male
125  23.0       F
126  41.0       M
127  43.0    Male
128   0.0    male
129  50.0       F
130  40.0  Female
131  43.0  Female
132   NaN     NaN
133  25.0    Male
134  49.0  Female
135   NaN  female
136  49.0       M
137  54.0   Male
138  42.0    male
139  30.0  Female
140  54.0  female
141  42.0  Female
142  23.0   Male
143  49.0    male
144  40.0     NaN
145  47.0    Male
146  54.0     NaN
147  49.0  female
148  22.0       M
149  49.0       F
150  48.0    Male
151   NaN       F
152  43.0  female
153   NaN  female
154  36.0  female
155  32.0       M
156  23.0   Male
157  33.0  Female
158  45.0  female
159  26.0  female
160  49.0  female
161  38.0       M
162  25.0    Male
163  49.0   Male
164  32.0    male
165  39.0  Female
166  43.0    male
167  35.0    Male
168  29.0     NaN
169  29.0  female
170   NaN       M
171  39.0    male
172  31.0  female
173   0.0    Male
174  36.0    Male
175  34.0  female
176  27.0     NaN
177  45.0  female
178  52.0     NaN
179  39.0    Male
180  44.0       F
181  53.0  Female
182   NaN   Male
183  42.0       M
184  40.0     NaN
185  42.0    Male
186  35.0   Male
187  33.0   Male
188  51.0       F
189   NaN  female
190  38.0       F
191   NaN   Male
192  39.0     NaN
193  38.0       F
194  27.0       M
195  51.0    Male
196  32.0       M
197   0.0     NaN
198  28.0       M
199  32.0  female

In [20]:
print(data.loc[1])

Employee_ID                                     2
Employee_Name                         Arun Sharma
Age                                          34.0
Gender                                          F
Department                                finance
City                                      Chennai
Email                    arun.sharma2@company.com
Employment_Type                          contract
Salary                                      53000
Joining_Date                           2023-09-01
Performance_Score                             6.0
Attendance_Percentage                         NaN
Name: 1, dtype: object

In [21]:
data = pd.read_csv("C:\\Users\\Admin\\OneDrive\\Documents\\CourseNotes\\employee_data_cleaning_practice_200_rows.csv",index_col="Employee_ID")

In [24]:
print(data.iloc[2])

Employee_Name                       Anitha Rao
Age                                       17.0
Gender                                    male
Department                          Operations
City                                   chennai
Email                    anitha.rao3@gmail.com
Employment_Type                      Part-Time
Salary                                   58000
Joining_Date                        2018-01-27
Performance_Score                          4.0
Attendance_Percentage                    100.0
Name: 3, dtype: object

In [25]:
print(data.to_string())

               Employee_Name   Age  Gender         Department        City                         Email Employment_Type     Salary Joining_Date  Performance_Score  Attendance_Percentage
Employee_ID
1                Sneha Kumar  38.0  Female            finance   Bangalore        sneha.kumar1@gmail.com       Part time      53000   2020-07-03                NaN                   75.0
2                Arun Sharma  34.0       F            finance     Chennai      arun.sharma2@company.com        contract      53000   2023-09-01                6.0                    NaN
3                 Anitha Rao  17.0    male         Operations     chennai         anitha.rao3@gmail.com       Part-Time      58000   2018-01-27                4.0                  100.0
4               Sneha Sharma  45.0    Male          Marketing     Chennai       sneha.sharma4@yahoo.com        contract      33000   2022-01-10                0.0                   -5.0
5                  Sneha Das  26.0       F         Operations     Chennai        sneha.das5@company.com        contract     103000   2021-04-15                2.0                   75.0
6                Anitha Iyer  26.0  female   Human Resources         Pune        anitha.iyer6@yahoo.com       Part-Time      53000   2019-02-18                3.5                  100.0
7                 Vijay Iyer  25.0       M              Sales    Hyderbad         vijay.iyer7@gmail.com       full time     113000   2025-02-13                NaN                   95.0
8                Nisha Reddy  41.0    male                 it       Delhi        nisha.reddy8@gmail.com       Full-Time      23000   2020-07-27                4.0                  100.0
9                  Vijay Rao  46.0       F            Finance        Pune          vijay.rao9@gmail.com        contract     118000   2023-02-23                6.0                   -5.0
10             Suresh Joseph  48.0     NaN            Finance      Mumbai     suresh.joseph10@yahoo.com       Full-Time     108000   2022-06-24                1.0                   80.0
11             Karthik Patel  48.0     NaN              SALES     chennai     karthik.patel11@yahoo.com       Part time     113000   2018-09-18                5.0                   -5.0
12               Arun Sharma  55.0   Male           Marketing   Bangalore       arun.sharma12@yahoo.com       Part-Time      58000   2025-03-10                0.0                   75.0
13               Suresh Nair  32.0       F            finance        Pune     suresh.nair13@company.com       Part-Time      98000   2019-03-12                3.5                   85.0
14                Nisha Nair  21.0  female                 HR     Chennai        nisha.nair14@yahoo.com             NaN     113000   2021-08-20                5.0                   90.0
15               Priya Reddy   0.0       M                 HR  BANGALORE      priya.reddy15@company.com       Part-Time      28000   2018-12-17                0.0                   -5.0
16                Divya Iyer  54.0    male              Sales    Hyderbad        divya.iyer16@gmail.com       full time     113000   2022-09-30                3.5                  105.0
17                 hari rao   28.0       F                 IT       Delhi          hari.rao17@gmail.com       Part time      53000   2020-07-09                4.0                   75.0
18               Rahul Kumar  35.0       F            finance   Bangalore       rahul.kumar18@yahoo.com        Contract      28000   2018-05-09                0.0                   90.0
19               Nisha Patel   NaN       F                 it  BANGALORE        nisha.patel19@gmail.com       Full-Time     108000   2023-04-21                2.0                    NaN
20                 Pooja Das  47.0   Male                  IT   Bangalore         pooja.das20@gmail.com        contract      88000   2026-03-06                3.5                   80.0
21              Anitha Reddy  33.0    male            Finance     chennai      anitha.reddy21@gmail.com       full time     103000   2023-01-12                4.0                   80.0
22                Manoj Nair  27.0       F                 HR     Chennai      manoj.nair22@company.com       Part-Time      23000   2025-04-25                NaN                  105.0
23               Deepa Reddy  46.0    male                 it     Chennai      deepa.reddy23 @yahoo.com             NaN      23000   2019-11-06                0.0                   95.0
24                Kavya Nair  52.0    Male                 IT      Mumbai        kavya.nair24@yahoo.com        contract      38000   2020-02-17                3.5                   75.0
25              Priya Joseph  51.0  Female            finance     Chennai      priya.joseph25@gmail.com             NaN      98000   2023-12-16                3.0                   80.0
26             Swetha Sharma  36.0    Male              SALES      Mumbai   swetha.sharma26@company.com       Part time      78000   2019-05-07                2.0                    NaN
E027            Gokul Joseph  54.0    male              Sales       Delhi      gokul.joseph27@gmail.com       full time      68000   2020-12-04                3.0                   95.0
28               Manoj Singh  25.0  Female                 HR     Chennai     manoj.singh28@company.com       Part time      18000   2023-02-21                4.0                   -5.0
29              Suresh Patel  43.0     NaN            Finance        Pune                 invalid-email             NaN      28000   2020-09-27                6.0                   95.0
30               Swetha Nair  21.0    male            Finance   Bangalore       swetha.nair30@yahoo.com       Full-Time        NaN   2024-03-21                2.0                   -5.0
31              Karthik Iyer  39.0    male              Sales       Delhi    karthik.iyer31@company.com       Part time  45000 INR   2020-05-12                0.0                   95.0
32              Priya Sharma  48.0    male            Finance       Delhi      priya.sharma32@gmail.com       Part-Time      58000   2018-06-30                0.0                   -5.0
33                Kavya Nair  21.0    Male            finance   Hyderabad      kavya.nair33@company.com             NaN      33000   2018-11-05                3.5                   -5.0
34              karthik das   29.0       F         Operations     Chennai       karthik.das34@yahoo.com        contract      23000   2021-06-16                4.0                   80.0
35                Pooja Nair  47.0       M            Finance      Mumbai        pooja.nair35@gmail.com       full time     113000   2026-05-28                1.0                   85.0
36                  Ravi Das  36.0    Male                 it   Bangalore        ravi.das36@company.com             NaN      58000   2019-10-15                0.0                   90.0
37                 Vijay Rao  43.0   Male               Sales     Chennai         vijay.rao37@gmail.com        Contract      63000   21/07/2020                5.0                   80.0
38              Suresh Singh   NaN  Female                 IT       Delhi    suresh.singh38@company.com        Contract      78000   2025-08-15                3.0                   95.0
39              Priya Sharma  65.0  Female                 it       Delhi    priya.sharma39@company.com       full time      83000   2021-11-16                4.0                   95.0
40                 Priya Das  21.0   Male          Operations      Mumbai       priya.das40@company.com       Full-Time      98000   2024-01-15                3.5                  100.0
41                Sneha Iyer  53.0    male                 it       Delhi        sneha.iyer41@yahoo.com       Part time      63000   06-24-2025                3.0                   90.0
42                 Kavya Das  32.0    Male            finance     chennai         kavya.das42@yahoo.com        Contract     113000   2024-05-20                5.0                   90.0
43              Kavya Joseph  65.0     NaN   Human Resources     Chennai       kavya.joseph43@yahoo.com        contract     118000   2021-08-12                4.0                   -5.0
44               Deepa Patel  26.0  Female         Operations     Chennai     deepa.patel44@company.com             NaN      63000   2023-10-13                4.0                   95.0
45              Anitha Reddy  30.0  Female              SALES  BANGALORE       anitha.reddy45@gmail.com       full time      18000   2018-07-09                NaN                   90.0
46                  Ajay Rao  46.0   Male                  HR     Chennai       ajay.rao46 @company.com       Part-Time      53000   2019-08-28                3.0                   -5.0
47               Manoj Kumar   NaN  female   Human Resources    Hyderabad       manoj.kumar47@yahoo.com             NaN      53000          NaN                0.0                   -5.0
48                Kavya Nair  49.0       F          Marketing  BANGALORE         kavya.nair48@yahoo.com             NaN      43000   2026-05-05                5.0                   -5.0
49               Deepa Reddy  38.0    male              Sales        Pune     deepa.reddy49@company.com        Contract      88000   2018-11-14                3.5                   -5.0
50               Rahul Patel  30.0  Female              Sales   Hyderabad     rahul.patel50@company.com       full time      53000   2022-04-18                NaN                  100.0
51                nisha rao   47.0    Male              SALES     chennai         nisha.rao51@yahoo.com             NaN      23000   2020-04-27                NaN                  105.0
52                Arun Singh  40.0       F              SALES    Hyderbad      arun.singh52@company.com       full time      78000   2022-09-13                4.0                   95.0
53                 Kavya Rao  22.0       M                NaN     chennai       kavya.rao53@company.com             NaN      78000   2021-10-08                0.0                   85.0
E054             Swetha Nair  22.0   Male                  HR     Chennai     swetha.nair54@company.com       Part-Time      78000   2024-08-21                0.0                   85.0
55                Priya Iyer  45.0   Male          Operations       Delhi        priya.iyer55@yahoo.com        Contract      68000   2020-05-16                NaN                   95.0
56                 Rahul Rao  22.0  Female              Sales       Delhi         rahul.rao56@gmail.com             NaN          0   2024-01-19                1.0                   75.0
57              Anitha Reddy   NaN  Female   Human Resources    Hyderabad      anitha.reddy57@gmail.com       Part time     113000   2019-09-17                4.0                  105.0
58              Suresh Singh  31.0    male            Finance   Bangalore                 invalid-email       Full-Time     113000   2024-10-23                1.0                   95.0
59                 Gokul Das  46.0  Female              Sales     Chennai         gokul.das59@gmail.com        contract     -25000   2020-03-23                5.0                   80.0
60               Gokul Kumar  43.0  female                 HR       Delhi     gokul.kumar60@company.com       Full-Time     103000   2022-10-21                NaN                  105.0
61                 Sneha Das  44.0       M                 it   Hyderabad       sneha.das61@company.com        contract     118000   2023-02-27                6.0                   95.0
62               Swetha Nair  51.0  female          Marketing     Chennai     swetha.nair62@company.com             NaN  45000 INR   2022-11-20                4.0                   80.0
63                Suresh Rao  36.0    Male         Operations     chennai      suresh.rao63@company.com       full time      88000   2024-05-23                3.5                   85.0
64               Deepa Reddy  43.0    Male          Marketing     Chennai       deepa.reddy64@yahoo.com       Part time      58000   2021-10-26                4.0                   80.0
65                Anitha Das  52.0     NaN   Human Resources   BANGALORE       anitha.das65@company.com             NaN     103000   2020-09-11                1.0                   80.0
66               Meena Reddy  46.0     NaN         Operations     Chennai       meena.reddy66@yahoo.com       Part time     -25000   2020-09-23                6.0                  100.0
67                Kavya Nair  42.0    male          Marketing        Pune        kavya.nair67@yahoo.com       Part-Time      73000   2025-11-18                2.0                   90.0
68              ravi sharma   55.0    male   Human Resources       Mumbai       ravi.sharma68@gmail.com        contract     -25000   2020-01-29                6.0                   95.0
69               Sneha Reddy  39.0       M                 IT        Pune      sneha.reddy69 @gmail.com        Contract      53000   2022-01-18                1.0                   75.0
70                Nisha Iyer  29.0    male                 IT   Bangalore        nisha.iyer70@yahoo.com       full time     118000   2026-06-11                0.0                  105.0
71                Ravi Patel  24.0     NaN                 it   Bangalore        ravi.patel71@gmail.com       Full-Time      58000   2023-05-11                1.0                   85.0
72            Karthik Joseph  40.0       F                 it    Hyderbad    karthik.joseph72@gmail.com             NaN      28000   2020-10-13                6.0                    NaN
73                 Manoj Rao  40.0    Male              SALES     Chennai         manoj.rao73@yahoo.com       Part time     108000   2022-10-23                2.0                   90.0
74                Vijay Iyer  26.0       M                 HR    Hyderbad        vijay.iyer74@gmail.com       Full-Time      43000   09/09/2020                NaN                  105.0
75                Swetha Rao  39.0  Female   Human Resources         Pune        swetha.rao75@yahoo.com        contract      23000   2020-08-06                4.0                   95.0
76               Gokul Reddy   NaN       M          Marketing   Hyderabad       gokul.reddy76@gmail.com       Full-Time      33000   2024-02-09                1.0                   85.0
77              Meena Joseph   0.0   Male           Marketing  BANGALORE       meena.joseph77@gmail.com        Contract      63000   2022-12-04                6.0                   -5.0
78                 Deepa Rao  26.0    male              SALES       Delhi         deepa.rao78@yahoo.com       Full-Time     113000   2018-06-13                2.0                   90.0
79              Gokul Joseph  22.0     NaN            Finance     Chennai    gokul.joseph79@company.com       Part time        NaN   2021-01-08                0.0                   95.0
80              Divya Joseph  48.0   Male          Operations  BANGALORE       divya.joseph80@gmail.com        Contract     118000   2023-07-08                3.5                   80.0
E081             Divya Singh  47.0    Male            finance     chennai       divya.singh81@yahoo.com       full time     -25000   2023-07-23                2.0                  100.0
82              Suresh Singh  28.0   Male    Human Resources     Hyderbad      suresh.singh82@gmail.com       Full-Time      78000   10-09-2023                4.0                   -5.0
83              Pooja Joseph  52.0       M          Marketing      Mumbai      pooja.joseph83@gmail.com        Contract     118000   2022-12-16                0.0                  105.0
84               Sneha Kumar  65.0    Male            finance        Pune       sneha.kumar84@gmail.com       Part time      53000   2025-12-17                NaN                   80.0
85            anitha sharma   50.0    male          Marketing  BANGALORE      anitha.sharma85@gmail.com       full time      33000   2025-04-07                0.0                  105.0
86                Anitha Rao   NaN       M              SALES    Chennai         anitha.rao86@gmail.com             NaN      38000   2022-04-21                2.0                   95.0
87               Kavya Singh  53.0     NaN              SALES        Pune                 invalid-email             NaN      58000   2018-01-11                3.0                  105.0
88                 Nisha Rao  43.0  female   Human Resources      chennai       nisha.rao88@company.com             NaN      68000   2024-03-10                4.0                   90.0
89                 Gokul Das  35.0   Male                  it  BANGALORE          gokul.das89@yahoo.com        contract      83000   2018-06-28                3.0                  105.0
90               Priya Patel  53.0     NaN                 HR  BANGALORE        priya.patel90@gmail.com       Full-Time     108000   2021-09-21                3.0                    NaN
91            Karthik Sharma  51.0  female                 HR     chennai  karthik.sharma91@company.com             NaN      58000   2021-10-18                6.0                    NaN
92                  Ravi Rao  55.0       F          Marketing      Mumbai         ravi.rao92 @gmail.com        contract      23000   2024-12-04                2.0                    NaN
93              Sneha Sharma  49.0  female                 IT     Chennai      sneha.sharma93@yahoo.com             NaN  45000 INR   2025-10-13                1.0                   95.0
94               Pooja Singh  48.0       M              SALES     chennai     pooja.singh94@company.com       Part-Time      38000          NaN                3.0                   80.0
95                Swetha Das   NaN    male   Human Resources       Mumbai        swetha.das95@gmail.com       full time      93000   2024-07-16                5.0                   75.0
96                Manoj Iyer  55.0    male              SALES       Delhi        manoj.iyer96@yahoo.com        contract      43000   2018-10-30                NaN                   95.0
97                Manoj Iyer  33.0  female                 it      Mumbai        manoj.iyer97@gmail.com       Part time      78000   2023-06-03                5.0                   95.0
98                  Arun Das  38.0     NaN              SALES     Chennai        arun.das98@company.com             NaN      18000   2024-05-07                5.0                   90.0
99              Swetha Singh  35.0  Female            Finance        Pune    swetha.singh99@company.com        contract     118000   2020-02-18                1.0                   95.0
100              Manoj Kumar  17.0  female          Marketing   Bangalore      manoj.kumar100@gmail.com        contract      73000   2026-03-19                NaN                   85.0
101              Vijay Patel  55.0    male            Finance        Pune    vijay.patel101@company.com             NaN      73000   2023-12-15                0.0                   95.0
102             ravi sharma   50.0  female            finance     chennai      ravi.sharma102@gmail.com       Full-Time      28000   2019-07-31                NaN                   75.0
103              Suresh Nair  28.0   Male               SALES        Pune    suresh.nair103@company.com             NaN      88000   2022-02-18                3.5                   80.0
104               Anitha Rao  22.0  Female              Sales     Chennai       anitha.rao104@yahoo.com        contract     113000   2024-04-18                0.0                   95.0
105             Kavya Sharma  29.0  Female                 HR  BANGALORE      kavya.sharma105@yahoo.com       Part-Time      23000   2018-06-02                6.0                   85.0
106                 Ajay Rao  44.0   Male                 NaN    Hyderbad       ajay.rao106@company.com       Part time        NaN   2026-05-02                3.0                    NaN

In [30]:
print(data.loc["2",["Employee_Name","Age"]])

Employee_Name    Arun Sharma
Age                     34.0
Name: 2, dtype: object

In [31]:
print(data.loc["2":"10",["Employee_Name","Age"]])

             Employee_Name   Age
Employee_ID
2              Arun Sharma  34.0
3               Anitha Rao  17.0
4             Sneha Sharma  45.0
5                Sneha Das  26.0
6              Anitha Iyer  26.0
7               Vijay Iyer  25.0
8              Nisha Reddy  41.0
9                Vijay Rao  46.0
10           Suresh Joseph  48.0

In [32]:
print(data.iloc[0])

Employee_Name                       Sneha Kumar
Age                                        38.0
Gender                                   Female
Department                              finance
City                                  Bangalore
Email                    sneha.kumar1@gmail.com
Employment_Type                       Part time
Salary                                    53000
Joining_Date                         2020-07-03
Performance_Score                           NaN
Attendance_Percentage                      75.0
Name: 1, dtype: object

In [37]:
print(data.iloc[0:5:2,1:4])

              Age  Gender  Department
Employee_ID
1            38.0  Female     finance
3            17.0    male  Operations
5            26.0       F  Operations

## filtering

In [38]:
f = data.copy()

In [39]:
f.to_string()

'               Employee_Name   Age  Gender         Department        City                         Email Employment_Type     Salary Joining_Date  Performance_Score  Attendance_Percentage\nEmployee_ID                                                                                                                                                                              \n1                Sneha Kumar  38.0  Female            finance   Bangalore        sneha.kumar1@gmail.com       Part time      53000   2020-07-03                NaN                   75.0\n2                Arun Sharma  34.0       F            finance     Chennai      arun.sharma2@company.com        contract      53000   2023-09-01                6.0                    NaN\n3                 Anitha Rao  17.0    male         Operations     chennai         anitha.rao3@gmail.com       Part-Time      58000   2018-01-27                4.0                  100.0\n4               Sneha Sharma  45.0    Male          Marketing     Chennai       sneha.sharma4@yahoo.com        contract      33000   2022-01-10                0.0                   -5.0\n5                  Sneha Das  26.0       F         Operations     Chennai        sneha.das5@company.com        contract     103000   2021-04-15                2.0                   75.0\n6                Anitha Iyer  26.0  female   Human Resources         Pune        anitha.iyer6@yahoo.com       Part-Time      53000   2019-02-18                3.5                  100.0\n7                 Vijay Iyer  25.0       M              Sales    Hyderbad         vijay.iyer7@gmail.com       full time     113000   2025-02-13                NaN                   95.0\n8                Nisha Reddy  41.0    male                 it       Delhi        nisha.reddy8@gmail.com       Full-Time      23000   2020-07-27                4.0                  100.0\n9                  Vijay Rao  46.0       F            Finance        Pune          vijay.rao9@gmail.com        contract     118000   2023-02-23                6.0                   -5.0\n10             Suresh Joseph  48.0     NaN            Finance      Mumbai     suresh.joseph10@yahoo.com       Full-Time     108000   2022-06-24                1.0                   80.0\n11             Karthik Patel  48.0     NaN              SALES     chennai     karthik.patel11@yahoo.com       Part time     113000   2018-09-18                5.0                   -5.0\n12               Arun Sharma  55.0   Male           Marketing   Bangalore       arun.sharma12@yahoo.com       Part-Time      58000   2025-03-10                0.0                   75.0\n13               Suresh Nair  32.0       F            finance        Pune     suresh.nair13@company.com       Part-Time      98000   2019-03-12                3.5                   85.0\n14                Nisha Nair  21.0  female                 HR     Chennai        nisha.nair14@yahoo.com             NaN     113000   2021-08-20                5.0                   90.0\n15               Priya Reddy   0.0       M                 HR  BANGALORE      priya.reddy15@company.com       Part-Time      28000   2018-12-17                0.0                   -5.0\n16                Divya Iyer  54.0    male              Sales    Hyderbad        divya.iyer16@gmail.com       full time     113000   2022-09-30                3.5                  105.0\n17                 hari rao   28.0       F                 IT       Delhi          hari.rao17@gmail.com       Part time      53000   2020-07-09                4.0                   75.0\n18               Rahul Kumar  35.0       F            finance   Bangalore       rahul.kumar18@yahoo.com        Contract      28000   2018-05-09                0.0                   90.0\n19               Nisha Patel   NaN       F                 it  BANGALORE        nisha.patel19@gmail.com       Full-Time     108000   2023-04-21                2.0                    NaN\n20                 Pooja Das  47.0   Male                  IT   Bangalore         pooja.das20@gmail.com        contract      88000   2026-03-06                3.5                   80.0\n21              Anitha Reddy  33.0    male            Finance     chennai      anitha.reddy21@gmail.com       full time     103000   2023-01-12                4.0                   80.0\n22                Manoj Nair  27.0       F                 HR     Chennai      manoj.nair22@company.com       Part-Time      23000   2025-04-25                NaN                  105.0\n23               Deepa Reddy  46.0    male                 it     Chennai      deepa.reddy23 @yahoo.com             NaN      23000   2019-11-06                0.0                   95.0\n24                Kavya Nair  52.0    Male                 IT      Mumbai        kavya.nair24@yahoo.com        contract      38000   2020-02-17                3.5                   75.0\n25              Priya Joseph  51.0  Female            finance     Chennai      priya.joseph25@gmail.com             NaN      98000   2023-12-16                3.0                   80.0\n26             Swetha Sharma  36.0    Male              SALES      Mumbai   swetha.sharma26@company.com       Part time      78000   2019-05-07                2.0                    NaN\nE027            Gokul Joseph  54.0    male              Sales       Delhi      gokul.joseph27@gmail.com       full time      68000   2020-12-04                3.0                   95.0\n28               Manoj Singh  25.0  Female                 HR     Chennai     manoj.singh28@company.com       Part time      18000   2023-02-21                4.0                   -5.0\n29              Suresh Patel  43.0     NaN            Finance        Pune                 invalid-email             NaN      28000   2020-09-27                6.0                   95.0\n30               Swetha Nair  21.0    male            Finance   Bangalore       swetha.nair30@yahoo.com       Full-Time        NaN   2024-03-21                2.0                   -5.0\n31              Karthik Iyer  39.0    male              Sales       Delhi    karthik.iyer31@company.com       Part time  45000 INR   2020-05-12                0.0                   95.0\n32              Priya Sharma  48.0    male            Finance       Delhi      priya.sharma32@gmail.com       Part-Time      58000   2018-06-30                0.0                   -5.0\n33                Kavya Nair  21.0    Male            finance   Hyderabad      kavya.nair33@company.com             NaN      33000   2018-11-05                3.5                   -5.0\n34              karthik das   29.0       F         Operations     Chennai       karthik.das34@yahoo.com        contract      23000   2021-06-16                4.0                   80.0\n35                Pooja Nair  47.0       M            Finance      Mumbai        pooja.nair35@gmail.com       full time     113000   2026-05-28                1.0                   85.0\n36                  Ravi Das  36.0    Male                 it   Bangalore        ravi.das36@company.com             NaN      58000   2019-10-15                0.0                   90.0\n37                 Vijay Rao  43.0   Male               Sales     Chennai         vijay.rao37@gmail.com        Contract      63000   21/07/2020                5.0                   80.0\n38              Suresh Singh   NaN  Female                 IT       Delhi    suresh.singh38@company.com        Contract      78000   2025-08-15                3.0                   95.0\n39              Priya Sharma  65.0  Female                 it       Delhi    priya.sharma39@company.com       full time      83000   2021-11-16                4.0                   95.0\n40                 Priya Das  21.0   Male          Operations      Mumbai       priya.das40@company.com       Full-Time      98000   2024-01-15                3.5                  100.0\n41                Sneha Iyer  53.0    male                 it       Delhi        sneha.iyer41@yahoo.com       Part time      63000   06-24-2025                3.0                   90.0\n42                 Kavya Das  32.0    Male            finance     chennai         kavya.das42@yahoo.com        Contract     113000   2024-05-20                5.0                   90.0\n43              Kavya Joseph  65.0     NaN   Human Resources     Chennai       kavya.joseph43@yahoo.com        contract     118000   2021-08-12                4.0                   -5.0\n44               Deepa Patel  26.0  Female         Operations     Chennai     deepa.patel44@company.com             NaN      63000   2023-10-13                4.0                   95.0\n45              Anitha Reddy  30.0  Female              SALES  BANGALORE       anitha.reddy45@gmail.com       full time      18000   2018-07-09                NaN                   90.0\n46                  Ajay Rao  46.0   Male                  HR     Chennai       ajay.rao46 @company.com       Part-Time      53000   2019-08-28                3.0                   -5.0\n47               Manoj Kumar   NaN  female   Human Resources    Hyderabad       manoj.kumar47@yahoo.com             NaN      53000          NaN                0.0                   -5.0\n48                Kavya Nair  49.0       F          Marketing  BANGALORE         kavya.nair48@yahoo.com             NaN      43000   2026-05-05                5.0                   -5.0\n49               Deepa Reddy  38.0    male              Sales        Pune     deepa.reddy49@company.com        Contract      88000   2018-11-14                3.5                   -5.0\n50               Rahul Patel  30.0  Female              Sales   Hyderabad     rahul.patel50@company.com       full time      53000   2022-04-18                NaN                  100.0\n51                nisha rao   47.0    Male              SALES     chennai         nisha.rao51@yahoo.com             NaN      23000   2020-04-27                NaN                  105.0\n52                Arun Singh  40.0       F              SALES    Hyderbad      arun.singh52@company.com       full time      78000   2022-09-13                4.0                   95.0\n53                 Kavya Rao  22.0       M                NaN     chennai       kavya.rao53@company.com             NaN      78000   2021-10-08                0.0                   85.0\nE054             Swetha Nair  22.0   Male                  HR     Chennai     swetha.nair54@company.com       Part-Time      78000   2024-08-21                0.0                   85.0\n55                Priya Iyer  45.0   Male          Operations       Delhi        priya.iyer55@yahoo.com        Contract      68000   2020-05-16                NaN                   95.0\n56                 Rahul Rao  22.0  Female              Sales       Delhi         rahul.rao56@gmail.com             NaN          0   2024-01-19                1.0                   75.0\n57              Anitha Reddy   NaN  Female   Human Resources    Hyderabad      anitha.reddy57@gmail.com       Part time     113000   2019-09-17                4.0                  105.0\n58              Suresh Singh  31.0    male            Finance   Bangalore                 invalid-email       Full-Time     113000   2024-10-23                1.0                   95.0\n59                 Gokul Das  46.0  Female              Sales     Chennai         gokul.das59@gmail.com        contract     -25000   2020-03-23                5.0                   80.0\n60               Gokul Kumar  43.0  female                 HR       Delhi     gokul.kumar60@company.com       Full-Time     103000   2022-10-21                NaN                  105.0\n61                 Sneha Das  44.0       M                 it   Hyderabad       sneha.das61@company.com        contract     118000   2023-02-27                6.0                   95.0\n62               Swetha Nair  51.0  female          Marketing     Chennai     swetha.nair62@company.com             NaN  45000 INR   2022-11-20                4.0                   80.0\n63                Suresh Rao  36.0    Male         Operations     chennai      suresh.rao63@company.com       full time      88000   2024-05-23                3.5                   85.0\n64               Deepa Reddy  43.0    Male          Marketing     Chennai       deepa.reddy64@yahoo.com       Part time      58000   2021-10-26                4.0                   80.0\n65                Anitha Das  52.0     NaN   Human Resources   BANGALORE       anitha.das65@company.com             NaN     103000   2020-09-11                1.0                   80.0\n66               Meena Reddy  46.0     NaN         Operations     Chennai       meena.reddy66@yahoo.com       Part time     -25000   2020-09-23                6.0                  100.0\n67                Kavya Nair  42.0    male          Marketing        Pune        kavya.nair67@yahoo.com       Part-Time      73000   2025-11-18                2.0                   90.0\n68              ravi sharma   55.0    male   Human Resources       Mumbai       ravi.sharma68@gmail.com        contract     -25000   2020-01-29                6.0                   95.0\n69               Sneha Reddy  39.0       M                 IT        Pune      sneha.reddy69 @gmail.com        Contract      53000   2022-01-18                1.0                   75.0\n70                Nisha Iyer  29.0    male                 IT   Bangalore        nisha.iyer70@yahoo.com       full time     118000   2026-06-11                0.0                  105.0\n71                Ravi Patel  24.0     NaN                 it   Bangalore        ravi.patel71@gmail.com       Full-Time      58000   2023-05-11                1.0                   85.0\n72            Karthik Joseph  40.0       F                 it    Hyderbad    karthik.joseph72@gmail.com             NaN      28000   2020-10-13                6.0                    NaN\n73                 Manoj Rao  40.0    Male              SALES     Chennai         manoj.rao73@yahoo.com       Part time     108000   2022-10-23                2.0                   90.0\n74                Vijay Iyer  26.0       M                 HR    Hyderbad        vijay.iyer74@gmail.com       Full-Time      43000   09/09/2020                NaN                  105.0\n75                Swetha Rao  39.0  Female   Human Resources         Pune        swetha.rao75@yahoo.com        contract      23000   2020-08-06                4.0                   95.0\n76               Gokul Reddy   NaN       M          Marketing   Hyderabad       gokul.reddy76@gmail.com       Full-Time      33000   2024-02-09                1.0                   85.0\n77              Meena Joseph   0.0   Male           Marketing  BANGALORE       meena.joseph77@gmail.com        Contract      63000   2022-12-04                6.0                   -5.0\n78                 Deepa Rao  26.0    male              SALES       Delhi         deepa.rao78@yahoo.com       Full-Time     113000   2018-06-13                2.0                   90.0\n79              Gokul Joseph  22.0     NaN            Finance     Chennai    gokul.joseph79@company.com       Part time        NaN   2021-01-08                0.0                   95.0\n80              Divya Joseph  48.0   Male          Operations  BANGALORE       divya.joseph80@gmail.com        Contract     118000   2023-07-08                3.5                   80.0\nE081             Divya Singh  47.0    Male            finance     chennai       divya.singh81@yahoo.com       full time     -25000   2023-07-23                2.0                  100.0\n82              Suresh Singh  28.0   Male    Human Resources     Hyderbad      suresh.singh82@gmail.com       Full-Time      78000   10-09-2023                4.0                   -5.0\n83              Pooja Joseph  52.0       M          Marketing      Mumbai      pooja.joseph83@gmail.com        Contract     118000   2022-12-16                0.0                  105.0\n84               Sneha Kumar  65.0    Male            finance        Pune       sneha.kumar84@gmail.com       Part time      53000   2025-12-17                NaN                   80.0\n85            anitha sharma   50.0    male          Marketing  BANGALORE      anitha.sharma85@gmail.com       full time      33000   2025-04-07                0.0                  105.0\n86                Anitha Rao   NaN       M              SALES    Chennai         anitha.rao86@gmail.com             NaN      38000   2022-04-21                2.0                   95.0\n87               Kavya Singh  53.0     NaN              SALES        Pune                 invalid-email             NaN      58000   2018-01-11                3.0                  105.0\n88                 Nisha Rao  43.0  female   Human Resources      chennai       nisha.rao88@company.com             NaN      68000   2024-03-10                4.0                   90.0\n89                 Gokul Das  35.0   Male                  it  BANGALORE          gokul.das89@yahoo.com        contract      83000   2018-06-28                3.0                  105.0\n90               Priya Patel  53.0     NaN                 HR  BANGALORE        priya.patel90@gmail.com       Full-Time     108000   2021-09-21                3.0                    NaN\n91            Karthik Sharma  51.0  female                 HR     chennai  karthik.sharma91@company.com             NaN      58000   2021-10-18                6.0                    NaN\n92                  Ravi Rao  55.0       F          Marketing      Mumbai         ravi.rao92 @gmail.com        contract      23000   2024-12-04                2.0                    NaN\n93              Sneha Sharma  49.0  female                 IT     Chennai      sneha.sharma93@yahoo.com             NaN  45000 INR   2025-10-13                1.0                   95.0\n94               Pooja Singh  48.0       M              SALES     chennai     pooja.singh94@company.com       Part-Time      38000          NaN                3.0                   80.0\n95                Swetha Das   NaN    male   Human Resources       Mumbai        swetha.das95@gmail.com       full time      93000   2024-07-16                5.0                   75.0\n96                Manoj Iyer  55.0    male              SALES       Delhi        manoj.iyer96@yahoo.com        contract      43000   2018-10-30                NaN                   95.0\n97                Manoj Iyer  33.0  female                 it      Mumbai        manoj.iyer97@gmail.com       Part time      78000   2023-06-03                5.0                   95.0\n98                  Arun Das  38.0     NaN              SALES     Chennai        arun.das98@company.com             NaN      18000   2024-05-07                5.0                   90.0\n99              Swetha Singh  35.0  Female            Finance        Pune    swetha.singh99@company.com        contract     118000   2020-02-18                1.0                   95.0\n100              Manoj Kumar  17.0  female          Marketing   Bangalore      manoj.kumar100@gmail.com        contract      73000   2026-03-19                NaN                   85.0\n101              Vijay Patel  55.0    male            Finance        Pune    vijay.patel101@company.com             NaN      73000   2023-12-15                0.0                   95.0\n102             ravi sharma   50.0  female            finance     chennai      ravi.sharma102@gmail.com       Full-Time      28000   2019-07-31                NaN                   75.0\n103              Suresh Nair  28.0   Male               SALES        Pune    suresh.nair103@company.com             NaN      88000   2022-02-18                3.5                   80.0\n104               Anitha Rao  22.0  Female              Sales     Chennai       anitha.rao104@yahoo.com        contract     113000   2024-04-18                0.0                   95.0\n105             Kavya Sharma  29.0  Female                 HR  BANGALORE      kavya.sharma105@yahoo.com       Part-Time      23000   2018-06-02                6.0               

In [44]:
f= data[data["Age"]>=40]
print(f)

             Employee_Name   Age Gender Department       City  \
Employee_ID
4             Sneha Sharma  45.0   Male  Marketing    Chennai
8              Nisha Reddy  41.0   male         it      Delhi
9                Vijay Rao  46.0      F    Finance       Pune
10           Suresh Joseph  48.0    NaN    Finance     Mumbai
11           Karthik Patel  48.0    NaN      SALES    chennai
...                    ...   ...    ...        ...        ...
184            Priya Patel  42.0      M      SALES  Hyderabad
185            Ajay Joseph  40.0    NaN    finance   Hyderbad
186             Arun Singh  42.0   Male  Marketing    Chennai
E189           Hari Joseph  51.0      F    finance  Hyderabad
196              Kavya Rao  51.0   Male  Marketing      Delhi

                                  Email Employment_Type     Salary  \
Employee_ID
4               sneha.sharma4@yahoo.com        contract      33000
8                nisha.reddy8@gmail.com       Full-Time      23000
9                  vijay.rao9@gmail.com        contract     118000
10            suresh.joseph10@yahoo.com       Full-Time     108000
11            karthik.patel11@yahoo.com       Part time     113000
...                                 ...             ...        ...
184           priya.patel184 @yahoo.com        Contract      93000
185          ajay.joseph185@company.com        contract     108000
186             arun.singh186@yahoo.com       Part time  45000 INR
E189           hari.joseph189@gmail.com       Part time          0
196              kavya.rao196@yahoo.com             NaN     118000

            Joining_Date  Performance_Score  Attendance_Percentage
Employee_ID
4             2022-01-10                0.0                   -5.0
8             2020-07-27                4.0                  100.0
9             2023-02-23                6.0                   -5.0
10            2022-06-24                1.0                   80.0
11            2018-09-18                5.0                   -5.0
...                  ...                ...                    ...
184           2023-10-29                3.5                   85.0
185           09/10/2021                5.0                  105.0
186           2019-03-25                0.0                   95.0
E189          2026-02-27                3.5                  105.0
196           2020-03-27                2.0                   90.0

[92 rows x 11 columns]

In [49]:
f=data[data["Gender"]!="Female"]

In [50]:
f

,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
Employee_ID,,,,,,,,,,,
2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,2023-09-01,6.0,NaN
3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,2018-01-27,4.0,100.0
4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,2022-01-10,0.0,-5.0
5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,2021-04-15,2.0,75.0
6,Anitha Iyer,26.0,female,Human Resources,Pune,anitha.iyer6@yahoo.com,Part-Time,53000,2019-02-18,3.5,100.0
...,...,...,...,...,...,...,...,...,...,...,...
196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,2020-03-27,2.0,90.0
197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,2019-12-22,5.0,75.0
198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,2019-03-16,6.0,105.0
199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,2019-10-28,3.5,95.0
200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,2025-03-01,NaN,80.0

In [52]:
f= data[(data["Gender"]=="Female") & (data["Age"]>=40)]
f

,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
Employee_ID,,,,,,,,,,,
25,Priya Joseph,51.0,Female,finance,Chennai,priya.joseph25@gmail.com,NaN,98000,2023-12-16,3.0,80.0
39,Priya Sharma,65.0,Female,it,Delhi,priya.sharma39@company.com,full time,83000,2021-11-16,4.0,95.0
59,Gokul Das,46.0,Female,Sales,Chennai,gokul.das59@gmail.com,contract,-25000,2020-03-23,5.0,80.0
120,Vijay Patel,51.0,Female,Operations,Hyderbad,vijay.patel120@yahoo.com,NaN,53000,2019-03-20,5.0,90.0
131,Rahul Das,40.0,Female,Finance,Delhi,rahul.das131@gmail.com,Part time,0,2021-10-22,2.0,-5.0
132,Hari Reddy,43.0,Female,Sales,Hyderabad,hari.reddy132@company.com,Part-Time,73000,2026-02-27,5.0,90.0
E135,Meena Rao,49.0,Female,HR,Pune,meena.rao135@yahoo.com,Part time,23000,2018-08-22,6.0,NaN
142,Divya Reddy,42.0,Female,Finance,Hyderabad,divya.reddy142@gmail.com,Contract,93000,2020-02-26,2.0,-5.0
182,Rahul Das,53.0,Female,SALES,Chennai,rahul.das182@yahoo.com,Part-Time,88000,2024-03-02,2.0,NaN

## Aggregate

In [54]:
data.mean(numeric_only=True)

Age                      38.137363
Performance_Score         3.150000
Attendance_Percentage    77.333333
dtype: float64

In [55]:
data.min(numeric_only=True)

Age                      0.0
Performance_Score        0.0
Attendance_Percentage   -5.0
dtype: float64

In [56]:
data.count(numeric_only=True)

Age                      182
Performance_Score        180
Attendance_Percentage    180
dtype: int64

In [59]:
data["Salary"].count()

np.int64(193)

In [60]:
data["Salary"].min()

'-25000'

In [61]:
data["Salary"].max()

'98000'

In [62]:
data["Salary"].

'530005300058000330001030005300011300023000118000108000113000580009800011300028000113000530002800010800088000103000230002300038000980007800068000180002800045000 INR5800033000230001130005800063000780008300098000630001130001180006300018000530005300043000880005300023000780007800078000680000113000113000-2500010300011800045000 INR8800058000103000-2500073000-2500053000118000580002800010800043000230003300063000113000118000-2500078000118000530003300038000580006800083000108000580002300045000 INR3800093000430007800018000118000730007300028000880001130002300058000118000230006800038000980009800010300008300083000730005300018000380008300045000 INR5800053000330002800078000-2500007300011800093000230000330001130003300073000280009300023000930004300033000730006800011300033000113000530001800045000 INR48000630006800083000113000118000530002800093000-25000-250003300011300068000230002800010800058000680006800011300063000930007800088000730009300010800045000 INR0180000430001030000-2500038000830001180008300011300068000113000'

In [63]:
# group by

In [64]:
group = data.groupby("Employment_Type")
group

In [66]:
print(group.min(numeric_only=True))

                  Age  Performance_Score  Attendance_Percentage
Employment_Type
Contract          0.0                0.0                   -5.0
Full-Time         0.0                0.0                   -5.0
Part time        22.0                0.0                   -5.0
Part-Time         0.0                0.0                   -5.0
contract         17.0                0.0                   -5.0
full time         0.0                0.0                   -5.0

In [67]:
## cleaning

In [70]:
d = data.dropna(subset= ["Performance_Score"])

In [71]:
d

,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
Employee_ID,,,,,,,,,,,
2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,2023-09-01,6.0,NaN
3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,2018-01-27,4.0,100.0
4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,2022-01-10,0.0,-5.0
5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,2021-04-15,2.0,75.0
6,Anitha Iyer,26.0,female,Human Resources,Pune,anitha.iyer6@yahoo.com,Part-Time,53000,2019-02-18,3.5,100.0
...,...,...,...,...,...,...,...,...,...,...,...
195,Anitha Kumar,27.0,M,HR,BANGALORE,anitha.kumar195@company.com,Full-Time,83000,2021-09-14,6.0,85.0
196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,2020-03-27,2.0,90.0
197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,2019-12-22,5.0,75.0
198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,2019-03-16,6.0,105.0
199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,2019-10-28,3.5,95.0

In [74]:
d = data.fillna({"Performance_Score":0})

In [75]:
d

,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
Employee_ID,,,,,,,,,,,
1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,2020-07-03,0.0,75.0
2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,2023-09-01,6.0,NaN
3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,2018-01-27,4.0,100.0
4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,2022-01-10,0.0,-5.0
5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,2021-04-15,2.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...
196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,2020-03-27,2.0,90.0
197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,2019-12-22,5.0,75.0
198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,2019-03-16,6.0,105.0
199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,2019-10-28,3.5,95.0
200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,2025-03-01,0.0,80.0

In [76]:
data["Gender"]=data["Gender"].replace({"f":"Female"})
data

,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
Employee_ID,,,,,,,,,,,
1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,2020-07-03,NaN,75.0
2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,2023-09-01,6.0,NaN
3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,2018-01-27,4.0,100.0
4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,2022-01-10,0.0,-5.0
5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,2021-04-15,2.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...
196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,2020-03-27,2.0,90.0
197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,2019-12-22,5.0,75.0
198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,2019-03-16,6.0,105.0
199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,2019-10-28,3.5,95.0
200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,2025-03-01,NaN,80.0

In [77]:
data["Gender"]=data["Gender"].replace({"F":"Female"})

In [78]:
data

,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
Employee_ID,,,,,,,,,,,
1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,2020-07-03,NaN,75.0
2,Arun Sharma,34.0,Female,finance,Chennai,arun.sharma2@company.com,contract,53000,2023-09-01,6.0,NaN
3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,2018-01-27,4.0,100.0
4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,2022-01-10,0.0,-5.0
5,Sneha Das,26.0,Female,Operations,Chennai,sneha.das5@company.com,contract,103000,2021-04-15,2.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...
196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,2020-03-27,2.0,90.0
197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,2019-12-22,5.0,75.0
198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,2019-03-16,6.0,105.0
199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,2019-10-28,3.5,95.0
200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,2025-03-01,NaN,80.0

In [79]:
data["Gender"]=data["Gender"].replace({"male":"Male","M":"Male","m":"Male"})

In [80]:
data

,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
Employee_ID,,,,,,,,,,,
1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,2020-07-03,NaN,75.0
2,Arun Sharma,34.0,Female,finance,Chennai,arun.sharma2@company.com,contract,53000,2023-09-01,6.0,NaN
3,Anitha Rao,17.0,Male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,2018-01-27,4.0,100.0
4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,2022-01-10,0.0,-5.0
5,Sneha Das,26.0,Female,Operations,Chennai,sneha.das5@company.com,contract,103000,2021-04-15,2.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...
196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,2020-03-27,2.0,90.0
197,Nisha Kumar,32.0,Male,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,2019-12-22,5.0,75.0
198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,2019-03-16,6.0,105.0
199,Suresh Reddy,28.0,Male,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,2019-10-28,3.5,95.0
200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,2025-03-01,NaN,80.0

In [82]:
import numpy as np
data["Age"]=data["Age"].astype(np.int64)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [83]:
d = data.drop_duplicates()
d

,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
Employee_ID,,,,,,,,,,,
1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,2020-07-03,NaN,75.0
2,Arun Sharma,34.0,Female,finance,Chennai,arun.sharma2@company.com,contract,53000,2023-09-01,6.0,NaN
3,Anitha Rao,17.0,Male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,2018-01-27,4.0,100.0
4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,2022-01-10,0.0,-5.0
5,Sneha Das,26.0,Female,Operations,Chennai,sneha.das5@company.com,contract,103000,2021-04-15,2.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...
196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,2020-03-27,2.0,90.0
197,Nisha Kumar,32.0,Male,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,2019-12-22,5.0,75.0
198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,2019-03-16,6.0,105.0
199,Suresh Reddy,28.0,Male,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,2019-10-28,3.5,95.0
200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,2025-03-01,NaN,80.0

In [90]:
excel = pd.read_excel("C:\\Users\\Admin\\OneDrive\\Documents\\CourseNotes\\DA\\excel\\Data_Analyst_Practice_Dataset.xlsx",sheet_name="Sheet1")

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Admin\\OneDrive\\Documents\\CourseNotes\\DA\\excel\\Data_Analyst_Practice_Dataset.xlsx'

In [86]:
pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\Admin\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Admin\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [88]:
excel.head()

,OrderID,Date,CustomerID,ProductID,EmpID,City,State,Qty,UnitPrice,Discount,Sales
0,O0001,2026-02-07,C205,P004,E026,Coimbatore,TN,1,15000,0,15000
1,O0002,2026-03-15,C172,P002,E017,Hyderabad,TS,7,700,0,4900
2,O0003,2026-03-15,C042,P004,E096,Pune,MH,2,15000,10,27000
3,O0004,2026-05-28,C125,P002,E085,Bangalore,KA,9,700,10,5670
4,O0005,2026-05-08,C160,P005,E053,Chennai,TN,9,18000,5,153900

In [91]:
import os

path = r"C:\Users\Admin\OneDrive\Documents\CourseNotes\DA\excel\Data_Analyst_Practice_Dataset.xlsx"

print(os.path.exists(path))

True