In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\Admin\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Admin\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
data = [22,33,44,55,66]
data

[22, 33, 44, 55, 66]

In [4]:
data = pd.Series(data)

In [5]:
data

0    22
1    33
2    44
3    55
4    66
dtype: int64

In [6]:
data[0]

np.int64(22)

In [7]:
data.loc[0]

np.int64(22)

In [80]:
data = pd.Series([10,20,30,40,32],index=["a","b","c","d","e"])

In [81]:
data

a    10
b    20
c    30
d    40
e    32
dtype: int64

In [83]:
data.loc["d"]

np.int64(40)

In [13]:
data.loc["c"]

np.int64(30)

In [11]:
data.iloc[0]

np.int64(10)

In [17]:
print(data[(data>=30) & (data<=35)])

c    30
e    32
dtype: int64

### DataFrame

In [19]:
d={
    'Name' : ['Vinoth','lathika','babu'],
    'age' : [22,23,24],
    'subject' : ['DA','ETL','genai']
}

In [20]:
d

{'Name': ['Vinoth', 'lathika', 'babu'],
 'age': [22, 23, 24],
 'subject': ['DA', 'ETL', 'genai']}

In [21]:
df = pd.DataFrame(d)

In [22]:
df

      Name  age subject
0   Vinoth   22      DA
1  lathika   23     ETL
2     babu   24   genai

In [23]:
df[0]

KeyError: 0

In [24]:
df.loc[0]

Name       Vinoth
age            22
subject        DA
Name: 0, dtype: object

In [26]:
df.loc[2]

Name        babu
age           24
subject    genai
Name: 2, dtype: object

In [31]:
print(df[df['age']>=23])

      Name  age subject
1  lathika   23     ETL
2     babu   24   genai

In [33]:
d1=pd.DataFrame({'Name':"devi",'age':23,'subject':'QA'},index=[3])

In [34]:
d1

   Name  age subject
3  devi   23      QA

In [35]:
df

      Name  age subject
0   Vinoth   22      DA
1  lathika   23     ETL
2     babu   24   genai

In [38]:
df=pd.concat([df,d1])

In [39]:
df

      Name  age subject
0   Vinoth   22      DA
1  lathika   23     ETL
2     babu   24   genai
3     devi   23      QA

In [46]:
df[(df['subject']=='QA') | (df['age']>=25)]

   Name  age subject
3  devi   23      QA

In [47]:
df[~ (df['subject']=='QA') | (df['age']>=25)]

      Name  age subject
0   Vinoth   22      DA
1  lathika   23     ETL
2     babu   24   genai

### Readfiles

In [49]:
file = pd.read_csv('C:\\Users\\Admin\\OneDrive\\Documents\\CourseNotes\\employee_data_cleaning_practice_200_rows.csv')

In [50]:
file

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,03-07-2020,NaN,75.0
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,01-09-2023,6.0,NaN
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,27-01-2018,4.0,100.0
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,10-01-2022,0.0,-5.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,15-04-2021,2.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,27-03-2020,2.0,90.0
196,197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,22-12-2019,5.0,75.0
197,198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,16-03-2019,6.0,105.0
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,28-10-2019,3.5,95.0
199,200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,01-03-2025,NaN,80.0

In [52]:
print(file.to_string())

    Employee_ID    Employee_Name   Age  Gender         Department        City                         Email Employment_Type     Salary Joining_Date  Performance_Score  Attendance_Percentage
0             1      Sneha Kumar  38.0  Female            finance   Bangalore        sneha.kumar1@gmail.com       Part time      53000   03-07-2020                NaN                   75.0
1             2      Arun Sharma  34.0       F            finance     Chennai      arun.sharma2@company.com        contract      53000   01-09-2023                6.0                    NaN
2             3       Anitha Rao  17.0    male         Operations     chennai         anitha.rao3@gmail.com       Part-Time      58000   27-01-2018                4.0                  100.0
3             4     Sneha Sharma  45.0    Male          Marketing     Chennai       sneha.sharma4@yahoo.com        contract      33000   10-01-2022                0.0                   -5.0
4             5        Sneha Das  26.0       F         Operations     Chennai        sneha.das5@company.com        contract     103000   15-04-2021                2.0                   75.0
5             6      Anitha Iyer  26.0  female   Human Resources         Pune        anitha.iyer6@yahoo.com       Part-Time      53000   18-02-2019                3.5                  100.0
6             7       Vijay Iyer  25.0       M              Sales    Hyderbad         vijay.iyer7@gmail.com       full time     113000   13-02-2025                NaN                   95.0
7             8      Nisha Reddy  41.0    male                 it       Delhi        nisha.reddy8@gmail.com       Full-Time      23000   27-07-2020                4.0                  100.0
8             9        Vijay Rao  46.0       F            Finance        Pune          vijay.rao9@gmail.com        contract     118000   23-02-2023                6.0                   -5.0
9            10    Suresh Joseph  48.0     NaN            Finance      Mumbai     suresh.joseph10@yahoo.com       Full-Time     108000   24-06-2022                1.0                   80.0
10           11    Karthik Patel  48.0     NaN              SALES     chennai     karthik.patel11@yahoo.com       Part time     113000   18-09-2018                5.0                   -5.0
11           12      Arun Sharma  55.0   Male           Marketing   Bangalore       arun.sharma12@yahoo.com       Part-Time      58000   10-03-2025                0.0                   75.0
12           13      Suresh Nair  32.0       F            finance        Pune     suresh.nair13@company.com       Part-Time      98000   12-03-2019                3.5                   85.0
13           14       Nisha Nair  21.0  female                 HR     Chennai        nisha.nair14@yahoo.com             NaN     113000   20-08-2021                5.0                   90.0
14           15      Priya Reddy   0.0       M                 HR  BANGALORE      priya.reddy15@company.com       Part-Time      28000   17-12-2018                0.0                   -5.0
15           16       Divya Iyer  54.0    male              Sales    Hyderbad        divya.iyer16@gmail.com       full time     113000   30-09-2022                3.5                  105.0
16           17        hari rao   28.0       F                 IT       Delhi          hari.rao17@gmail.com       Part time      53000   09-07-2020                4.0                   75.0
17           18      Rahul Kumar  35.0       F            finance   Bangalore       rahul.kumar18@yahoo.com        Contract      28000   09-05-2018                0.0                   90.0
18           19      Nisha Patel   NaN       F                 it  BANGALORE        nisha.patel19@gmail.com       Full-Time     108000   21-04-2023                2.0                    NaN
19           20        Pooja Das  47.0   Male                  IT   Bangalore         pooja.das20@gmail.com        contract      88000   06-03-2026                3.5                   80.0
20           21     Anitha Reddy  33.0    male            Finance     chennai      anitha.reddy21@gmail.com       full time     103000   12-01-2023                4.0                   80.0
21           22       Manoj Nair  27.0       F                 HR     Chennai      manoj.nair22@company.com       Part-Time      23000   25-04-2025                NaN                  105.0
22           23      Deepa Reddy  46.0    male                 it     Chennai      deepa.reddy23 @yahoo.com             NaN      23000   06-11-2019                0.0                   95.0
23           24       Kavya Nair  52.0    Male                 IT      Mumbai        kavya.nair24@yahoo.com        contract      38000   17-02-2020                3.5                   75.0
24           25     Priya Joseph  51.0  Female            finance     Chennai      priya.joseph25@gmail.com             NaN      98000   16-12-2023                3.0                   80.0
25           26    Swetha Sharma  36.0    Male              SALES      Mumbai   swetha.sharma26@company.com       Part time      78000   07-05-2019                2.0                    NaN
26         E027     Gokul Joseph  54.0    male              Sales       Delhi      gokul.joseph27@gmail.com       full time      68000   04-12-2020                3.0                   95.0
27           28      Manoj Singh  25.0  Female                 HR     Chennai     manoj.singh28@company.com       Part time      18000   21-02-2023                4.0                   -5.0
28           29     Suresh Patel  43.0     NaN            Finance        Pune                 invalid-email             NaN      28000   27-09-2020                6.0                   95.0
29           30      Swetha Nair  21.0    male            Finance   Bangalore       swetha.nair30@yahoo.com       Full-Time        NaN   21-03-2024                2.0                   -5.0
30           31     Karthik Iyer  39.0    male              Sales       Delhi    karthik.iyer31@company.com       Part time  45000 INR   12-05-2020                0.0                   95.0
31           32     Priya Sharma  48.0    male            Finance       Delhi      priya.sharma32@gmail.com       Part-Time      58000   30-06-2018                0.0                   -5.0
32           33       Kavya Nair  21.0    Male            finance   Hyderabad      kavya.nair33@company.com             NaN      33000   05-11-2018                3.5                   -5.0
33           34     karthik das   29.0       F         Operations     Chennai       karthik.das34@yahoo.com        contract      23000   16-06-2021                4.0                   80.0
34           35       Pooja Nair  47.0       M            Finance      Mumbai        pooja.nair35@gmail.com       full time     113000   28-05-2026                1.0                   85.0
35           36         Ravi Das  36.0    Male                 it   Bangalore        ravi.das36@company.com             NaN      58000   15-10-2019                0.0                   90.0
36           37        Vijay Rao  43.0   Male               Sales     Chennai         vijay.rao37@gmail.com        Contract      63000   21-07-2020                5.0                   80.0
37           38     Suresh Singh   NaN  Female                 IT       Delhi    suresh.singh38@company.com        Contract      78000   15-08-2025                3.0                   95.0
38           39     Priya Sharma  65.0  Female                 it       Delhi    priya.sharma39@company.com       full time      83000   16-11-2021                4.0                   95.0
39           40        Priya Das  21.0   Male          Operations      Mumbai       priya.das40@company.com       Full-Time      98000   15-01-2024                3.5                  100.0
40           41       Sneha Iyer  53.0    male                 it       Delhi        sneha.iyer41@yahoo.com       Part time      63000   06-24-2025                3.0                   90.0
41           42        Kavya Das  32.0    Male            finance     chennai         kavya.das42@yahoo.com        Contract     113000   20-05-2024                5.0                   90.0
42           43     Kavya Joseph  65.0     NaN   Human Resources     Chennai       kavya.joseph43@yahoo.com        contract     118000   12-08-2021                4.0                   -5.0
43           44      Deepa Patel  26.0  Female         Operations     Chennai     deepa.patel44@company.com             NaN      63000   13-10-2023                4.0                   95.0
44           45     Anitha Reddy  30.0  Female              SALES  BANGALORE       anitha.reddy45@gmail.com       full time      18000   09-07-2018                NaN                   90.0
45           46         Ajay Rao  46.0   Male                  HR     Chennai       ajay.rao46 @company.com       Part-Time      53000   28-08-2019                3.0                   -5.0
46           47      Manoj Kumar   NaN  female   Human Resources    Hyderabad       manoj.kumar47@yahoo.com             NaN      53000          NaN                0.0                   -5.0
47           48       Kavya Nair  49.0       F          Marketing  BANGALORE         kavya.nair48@yahoo.com             NaN      43000   05-05-2026                5.0                   -5.0
48           49      Deepa Reddy  38.0    male              Sales        Pune     deepa.reddy49@company.com        Contract      88000   14-11-2018                3.5                   -5.0
49           50      Rahul Patel  30.0  Female              Sales   Hyderabad     rahul.patel50@company.com       full time      53000   18-04-2022                NaN                  100.0
50           51       nisha rao   47.0    Male              SALES     chennai         nisha.rao51@yahoo.com             NaN      23000   27-04-2020                NaN                  105.0
51           52       Arun Singh  40.0       F              SALES    Hyderbad      arun.singh52@company.com       full time      78000   13-09-2022                4.0                   95.0
52           53        Kavya Rao  22.0       M                NaN     chennai       kavya.rao53@company.com             NaN      78000   08-10-2021                0.0                   85.0
53         E054      Swetha Nair  22.0   Male                  HR     Chennai     swetha.nair54@company.com       Part-Time      78000   21-08-2024                0.0                   85.0
54           55       Priya Iyer  45.0   Male          Operations       Delhi        priya.iyer55@yahoo.com        Contract      68000   16-05-2020                NaN                   95.0
55           56        Rahul Rao  22.0  Female              Sales       Delhi         rahul.rao56@gmail.com             NaN          0   19-01-2024                1.0                   75.0
56           57     Anitha Reddy   NaN  Female   Human Resources    Hyderabad      anitha.reddy57@gmail.com       Part time     113000   17-09-2019                4.0                  105.0
57           58     Suresh Singh  31.0    male            Finance   Bangalore                 invalid-email       Full-Time     113000   23-10-2024                1.0                   95.0
58           59        Gokul Das  46.0  Female              Sales     Chennai         gokul.das59@gmail.com        contract     -25000   23-03-2020                5.0                   80.0
59           60      Gokul Kumar  43.0  female                 HR       Delhi     gokul.kumar60@company.com       Full-Time     103000   21-10-2022                NaN                  105.0
60           61        Sneha Das  44.0       M                 it   Hyderabad       sneha.das61@company.com        contract     118000   27-02-2023                6.0                   95.0
61           62      Swetha Nair  51.0  female          Marketing     Chennai     swetha.nair62@company.com             NaN  45000 INR   20-11-2022                4.0                   80.0
62           63       Suresh Rao  36.0    Male         Operations     chennai      suresh.rao63@company.com       full time      88000   23-05-2024                3.5                   85.0
63           64      Deepa Reddy  43.0    Male          Marketing     Chennai       deepa.reddy64@yahoo.com       Part time      58000   26-10-2021                4.0                   80.0
64           65       Anitha Das  52.0     NaN   Human Resources   BANGALORE       anitha.das65@company.com             NaN     103000   11-09-2020                1.0                   80.0
65           66      Meena Reddy  46.0     NaN         Operations     Chennai       meena.reddy66@yahoo.com       Part time     -25000   23-09-2020                6.0                  100.0
66           67       Kavya Nair  42.0    male          Marketing        Pune        kavya.nair67@yahoo.com       Part-Time      73000   18-11-2025                2.0                   90.0
67           68     ravi sharma   55.0    male   Human Resources       Mumbai       ravi.sharma68@gmail.com        contract     -25000   29-01-2020                6.0                   95.0
68           69      Sneha Reddy  39.0       M                 IT        Pune      sneha.reddy69 @gmail.com        Contract      53000   18-01-2022                1.0                   75.0
69           70       Nisha Iyer  29.0    male                 IT   Bangalore        nisha.iyer70@yahoo.com       full time     118000   11-06-2026                0.0                  105.0
70           71       Ravi Patel  24.0     NaN                 it   Bangalore        ravi.patel71@gmail.com       Full-Time      58000   11-05-2023                1.0                   85.0
71           72   Karthik Joseph  40.0       F                 it    Hyderbad    karthik.joseph72@gmail.com             NaN      28000   13-10-2020                6.0                    NaN
72           73        Manoj Rao  40.0    Male              SALES     Chennai         manoj.rao73@yahoo.com       Part time     108000   23-10-2022                2.0                   90.0
73           74       Vijay Iyer  26.0       M                 HR    Hyderbad        vijay.iyer74@gmail.com       Full-Time      43000   09-09-2020                NaN                  105.0
74           75       Swetha Rao  39.0  Female   Human Resources         Pune        swetha.rao75@yahoo.com        contract      23000   06-08-2020                4.0                   95.0
75           76      Gokul Reddy   NaN       M          Marketing   Hyderabad       gokul.reddy76@gmail.com       Full-Time      33000   09-02-2024                1.0                   85.0
76           77     Meena Joseph   0.0   Male           Marketing  BANGALORE       meena.joseph77@gmail.com        Contract      63000   04-12-2022                6.0                   -5.0
77           78        Deepa Rao  26.0    male              SALES       Delhi         deepa.rao78@yahoo.com       Full-Time     113000   13-06-2018                2.0                   90.0
78           79     Gokul Joseph  22.0     NaN            Finance     Chennai    gokul.joseph79@company.com       Part time        NaN   08-01-2021                0.0                   95.0
79           80     Divya Joseph  48.0   Male          Operations  BANGALORE       divya.joseph80@gmail.com        Contract     118000   08-07-2023                3.5                   80.0
80         E081      Divya Singh  47.0    Male            finance     chennai       divya.singh81@yahoo.com       full time     -25000   23-07-2023                2.0                  100.0
81           82     Suresh Singh  28.0   Male    Human Resources     Hyderbad      suresh.singh82@gmail.com       Full-Time      78000   10-09-2023                4.0                   -5.0
82           83     Pooja Joseph  52.0       M          Marketing      Mumbai      pooja.joseph83@gmail.com        Contract     118000   16-12-2022                0.0                  105.0
83           84      Sneha Kumar  65.0    Male            finance        Pune       sneha.kumar84@gmail.com       Part time      53000   17-12-2025                NaN                   80.0
84           85   anitha sharma   50.0    male          Marketing  BANGALORE      anitha.sharma85@gmail.com       full time      33000   07-04-2025                0.0                  105.0
85           86       Anitha Rao   NaN       M              SALES    Chennai         anitha.rao86@gmail.com             NaN      38000   21-04-2022                2.0                   95.0
86           87      Kavya Singh  53.0     NaN              SALES        Pune                 invalid-email             NaN      58000   11-01-2018                3.0                  105.0
87           88        Nisha Rao  43.0  female   Human Resources      chennai       nisha.rao88@company.com             NaN      68000   10-03-2024                4.0                   90.0
88           89        Gokul Das  35.0   Male                  it  BANGALORE          gokul.das89@yahoo.com        contract      83000   28-06-2018                3.0                  105.0
89           90      Priya Patel  53.0     NaN                 HR  BANGALORE        priya.patel90@gmail.com       Full-Time     108000   21-09-2021                3.0                    NaN
90           91   Karthik Sharma  51.0  female                 HR     chennai  karthik.sharma91@company.com             NaN      58000   18-10-2021                6.0                    NaN
91           92         Ravi Rao  55.0       F          Marketing      Mumbai         ravi.rao92 @gmail.com        contract      23000   04-12-2024                2.0                    NaN
92           93     Sneha Sharma  49.0  female                 IT     Chennai      sneha.sharma93@yahoo.com             NaN  45000 INR   13-10-2025                1.0                   95.0
93           94      Pooja Singh  48.0       M              SALES     chennai     pooja.singh94@company.com       Part-Time      38000          NaN                3.0                   80.0
94           95       Swetha Das   NaN    male   Human Resources       Mumbai        swetha.das95@gmail.com       full time      93000   16-07-2024                5.0                   75.0
95           96       Manoj Iyer  55.0    male              SALES       Delhi        manoj.iyer96@yahoo.com        contract      43000   30-10-2018                NaN                   95.0
96           97       Manoj Iyer  33.0  female                 it      Mumbai        manoj.iyer97@gmail.com       Part time      78000   03-06-2023                5.0                   95.0
97           98         Arun Das  38.0     NaN              SALES     Chennai        arun.das98@company.com             NaN      18000   07-05-2024                5.0                   90.0
98           99     Swetha Singh  35.0  Female            Finance        Pune    swetha.singh99@company.com        contract     118000   18-02-2020                1.0                   95.0
99          100      Manoj Kumar  17.0  female          Marketing   Bangalore      manoj.kumar100@gmail.com        contract      73000   19-03-2026                NaN                   85.0
100         101      Vijay Patel  55.0    male            Finance        Pune    vijay.patel101@company.com             NaN      73000   15-12-2023                0.0                   95.0
101         102     ravi sharma   50.0  female            finance     chennai      ravi.sharma102@gmail.com       Full-Time      28000   31-07-2019                NaN                   75.0
102         103      Suresh Nair  28.0   Male               SALES        Pune    suresh.nair103@company.com             NaN      88000   18-02-2022                3.5                   80.0
103         104       Anitha Rao  22.0  Female              Sales     Chennai       anitha.rao104@yahoo.com        contract     113000   18-04-2024                0.0                   95.0

In [56]:
file.columns

Index(['Employee_ID', 'Employee_Name', 'Age', 'Gender', 'Department', 'City',
       'Email', 'Employment_Type', 'Salary', 'Joining_Date',
       'Performance_Score', 'Attendance_Percentage'],
      dtype='str')

In [57]:
file.head()

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,03-07-2020,NaN,75.0
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,01-09-2023,6.0,NaN
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,27-01-2018,4.0,100.0
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,10-01-2022,0.0,-5.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,15-04-2021,2.0,75.0

In [58]:
file.tail()

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
195,196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,27-03-2020,2.0,90.0
196,197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,22-12-2019,5.0,75.0
197,198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,16-03-2019,6.0,105.0
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,28-10-2019,3.5,95.0
199,200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,01-03-2025,NaN,80.0

In [60]:
file.head(100)

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,03-07-2020,NaN,75.0
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,01-09-2023,6.0,NaN
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,27-01-2018,4.0,100.0
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,10-01-2022,0.0,-5.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,15-04-2021,2.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Manoj Iyer,55.0,male,SALES,Delhi,manoj.iyer96@yahoo.com,contract,43000,30-10-2018,NaN,95.0
96,97,Manoj Iyer,33.0,female,it,Mumbai,manoj.iyer97@gmail.com,Part time,78000,03-06-2023,5.0,95.0
97,98,Arun Das,38.0,NaN,SALES,Chennai,arun.das98@company.com,NaN,18000,07-05-2024,5.0,90.0
98,99,Swetha Singh,35.0,Female,Finance,Pune,swetha.singh99@company.com,contract,118000,18-02-2020,1.0,95.0
99,100,Manoj Kumar,17.0,female,Marketing,Bangalore,manoj.kumar100@gmail.com,contract,73000,19-03-2026,NaN,85.0

In [61]:
file.tail(10)

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
190,191,Vijay Reddy,38.0,F,Marketing,Pune,vijay.reddy191@gmail.com,contract,103000,07-05-2021,0.0,100.0
191,192,Deepa Singh,NaN,Male,SALES,Bangalore,deepa.singh192@yahoo.com,full time,0,25-01-2021,3.5,85.0
192,193,Meena Kumar,39.0,NaN,Marketing,BANGALORE,meena.kumar193@yahoo.com,Part-Time,-25000,20-11-2018,4.0,-5.0
193,194,Suresh Nair,38.0,F,Sales,Chennai,suresh.nair194@company.com,Full-Time,38000,24-03-2019,6.0,90.0
194,195,Anitha Kumar,27.0,M,HR,BANGALORE,anitha.kumar195@company.com,Full-Time,83000,14-09-2021,6.0,85.0
195,196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,27-03-2020,2.0,90.0
196,197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,22-12-2019,5.0,75.0
197,198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,16-03-2019,6.0,105.0
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,28-10-2019,3.5,95.0
199,200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,01-03-2025,NaN,80.0

In [67]:
file[['Employee_ID','Employee_Name','Age']].head(10)

  Employee_ID  Employee_Name   Age
0           1    Sneha Kumar  38.0
1           2    Arun Sharma  34.0
2           3     Anitha Rao  17.0
3           4   Sneha Sharma  45.0
4           5      Sneha Das  26.0
5           6    Anitha Iyer  26.0
6           7     Vijay Iyer  25.0
7           8    Nisha Reddy  41.0
8           9      Vijay Rao  46.0
9          10  Suresh Joseph  48.0

In [68]:
file.describe()

              Age  Performance_Score  Attendance_Percentage
count  182.000000         180.000000             180.000000
mean    38.137363           3.150000              77.333333
std     12.475294           1.962569              35.138990
min      0.000000           0.000000              -5.000000
25%     29.000000           2.000000              80.000000
50%     40.000000           3.500000              90.000000
75%     48.000000           5.000000             100.000000
max     65.000000           6.000000             105.000000

In [69]:
file.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            200 non-null    str
 1   Employee_Name          200 non-null    str
 2   Age                    182 non-null    float64
 3   Gender                 177 non-null    str
 4   Department             197 non-null    str
 5   City                   200 non-null    str
 6   Email                  200 non-null    str
 7   Employment_Type        164 non-null    str
 8   Salary                 193 non-null    str
 9   Joining_Date           196 non-null    str
 10  Performance_Score      180 non-null    float64
 11  Attendance_Percentage  180 non-null    float64
dtypes: float64(3), str(9)
memory usage: 18.9 KB

In [73]:
file.head(20)

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,03-07-2020,NaN,75.0
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,01-09-2023,6.0,NaN
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,27-01-2018,4.0,100.0
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,10-01-2022,0.0,-5.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,15-04-2021,2.0,75.0
5,6,Anitha Iyer,26.0,female,Human Resources,Pune,anitha.iyer6@yahoo.com,Part-Time,53000,18-02-2019,3.5,100.0
6,7,Vijay Iyer,25.0,M,Sales,Hyderbad,vijay.iyer7@gmail.com,full time,113000,13-02-2025,NaN,95.0
7,8,Nisha Reddy,41.0,male,it,Delhi,nisha.reddy8@gmail.com,Full-Time,23000,27-07-2020,4.0,100.0
8,9,Vijay Rao,46.0,F,Finance,Pune,vijay.rao9@gmail.com,contract,118000,23-02-2023,6.0,-5.0
9,10,Suresh Joseph,48.0,NaN,Finance,Mumbai,suresh.joseph10@yahoo.com,Full-Time,108000,24-06-2022,1.0,80.0
10,11,Karthik Patel,48.0,NaN,SALES,chennai,karthik.patel11@yahoo.com,Part time,113000,18-09-2018,5.0,-5.0
11,12,Arun Sharma,55.0,Male,Marketing,Bangalore,arun.sharma12@yahoo.com,Part-Time,58000,10-03-2025,0.0,75.0
12,13,Suresh Nair,32.0,F,finance,Pune,suresh.nair13@company.com,Part-Time,98000,12-03-2019,3.5,85.0
13,14,Nisha Nair,21.0,female,HR,Chennai,nisha.nair14@yahoo.com,NaN,113000,20-08-2021,5.0,90.0
14,15,Priya Reddy,0.0,M,HR,BANGALORE,priya.reddy15@company.com,Part-Time,28000,17-12-2018,0.0,-5.0
15,16,Divya Iyer,54.0,male,Sales,Hyderbad,divya.iyer16@gmail.com,full time,113000,30-09-2022,3.5,105.0
16,17,hari rao,28.0,F,IT,Delhi,hari.rao17@gmail.com,Part time,53000,09-07-2020,4.0,75.0
17,18,Rahul Kumar,35.0,F,finance,Bangalore,rahul.kumar18@yahoo.com,Contract,28000,09-05-2018,0.0,90.0
18,19,Nisha Patel,NaN,F,it,BANGALORE,nisha.patel19@gmail.com,Full-Time,108000,21-04-2023,2.0,NaN
19,20,Pooja Das,47.0,Male,IT,Bangalore,pooja.das20@gmail.com,contract,88000,06-03-2026,3.5,80.0

In [76]:
file.loc[10:20]

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
10,11,Karthik Patel,48.0,NaN,SALES,chennai,karthik.patel11@yahoo.com,Part time,113000,18-09-2018,5.0,-5.0
11,12,Arun Sharma,55.0,Male,Marketing,Bangalore,arun.sharma12@yahoo.com,Part-Time,58000,10-03-2025,0.0,75.0
12,13,Suresh Nair,32.0,F,finance,Pune,suresh.nair13@company.com,Part-Time,98000,12-03-2019,3.5,85.0
13,14,Nisha Nair,21.0,female,HR,Chennai,nisha.nair14@yahoo.com,NaN,113000,20-08-2021,5.0,90.0
14,15,Priya Reddy,0.0,M,HR,BANGALORE,priya.reddy15@company.com,Part-Time,28000,17-12-2018,0.0,-5.0
15,16,Divya Iyer,54.0,male,Sales,Hyderbad,divya.iyer16@gmail.com,full time,113000,30-09-2022,3.5,105.0
16,17,hari rao,28.0,F,IT,Delhi,hari.rao17@gmail.com,Part time,53000,09-07-2020,4.0,75.0
17,18,Rahul Kumar,35.0,F,finance,Bangalore,rahul.kumar18@yahoo.com,Contract,28000,09-05-2018,0.0,90.0
18,19,Nisha Patel,NaN,F,it,BANGALORE,nisha.patel19@gmail.com,Full-Time,108000,21-04-2023,2.0,NaN
19,20,Pooja Das,47.0,Male,IT,Bangalore,pooja.das20@gmail.com,contract,88000,06-03-2026,3.5,80.0
20,21,Anitha Reddy,33.0,male,Finance,chennai,anitha.reddy21@gmail.com,full time,103000,12-01-2023,4.0,80.0

In [79]:
file.iloc[15:30:5]

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
15,16,Divya Iyer,54.0,male,Sales,Hyderbad,divya.iyer16@gmail.com,full time,113000,30-09-2022,3.5,105.0
20,21,Anitha Reddy,33.0,male,Finance,chennai,anitha.reddy21@gmail.com,full time,103000,12-01-2023,4.0,80.0
25,26,Swetha Sharma,36.0,Male,SALES,Mumbai,swetha.sharma26@company.com,Part time,78000,07-05-2019,2.0,NaN

In [95]:
file[["Employee_ID","Employee_Name","Age"]].loc[(file['Age']==30)]

    Employee_ID Employee_Name   Age
44           45  Anitha Reddy  30.0
49           50   Rahul Patel  30.0
139         140  Rahul Joseph  30.0

In [99]:
excel = pd.read_excel('C:\\Users\\Admin\\OneDrive\\Documents\\CourseNotes\\Data_Analyst_Practice_Dataset_excel.xlsx',sheet_name='')

In [98]:
pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\Admin\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Admin\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [100]:
excel

,OrderID,Date,CustomerID,ProductID,EmpID,City,State,Qty,UnitPrice,Discount,Sales
0,O0001,2026-02-07,C205,P004,E026,Coimbatore,TN,1,15000,0,15000
1,O0002,2026-03-15,C172,P002,E017,Hyderabad,TS,7,700,0,4900
2,O0003,2026-03-15,C042,P004,E096,Pune,MH,2,15000,10,27000
3,O0004,2026-05-28,C125,P002,E085,Bangalore,KA,9,700,10,5670
4,O0005,2026-05-08,C160,P005,E053,Chennai,TN,9,18000,5,153900
...,...,...,...,...,...,...,...,...,...,...,...
495,O0496,2026-01-12,C201,P004,E058,Chennai,TN,3,15000,15,38250
496,O0497,2026-01-30,C248,P005,E013,Pune,MH,6,18000,0,108000
497,O0498,2026-01-17,C199,P004,E058,Hyderabad,TS,6,15000,10,81000
498,O0499,2026-03-15,C076,P005,E028,Chennai,TN,8,18000,5,136800
499,O0500,2026-06-15,C218,P002,E082,Hyderabad,TS,1,700,10,630

In [101]:
excel[excel['Sales']>=1000]

,OrderID,Date,CustomerID,ProductID,EmpID,City,State,Qty,UnitPrice,Discount,Sales
0,O0001,2026-02-07,C205,P004,E026,Coimbatore,TN,1,15000,0,15000
1,O0002,2026-03-15,C172,P002,E017,Hyderabad,TS,7,700,0,4900
2,O0003,2026-03-15,C042,P004,E096,Pune,MH,2,15000,10,27000
3,O0004,2026-05-28,C125,P002,E085,Bangalore,KA,9,700,10,5670
4,O0005,2026-05-08,C160,P005,E053,Chennai,TN,9,18000,5,153900
...,...,...,...,...,...,...,...,...,...,...,...
494,O0495,2026-02-05,C137,P005,E015,Bangalore,KA,1,18000,15,15300
495,O0496,2026-01-12,C201,P004,E058,Chennai,TN,3,15000,15,38250
496,O0497,2026-01-30,C248,P005,E013,Pune,MH,6,18000,0,108000
497,O0498,2026-01-17,C199,P004,E058,Hyderabad,TS,6,15000,10,81000
498,O0499,2026-03-15,C076,P005,E028,Chennai,TN,8,18000,5,136800

In [106]:
excel[~(excel['Sales']>=1000) & (excel['State']=='TN')]

,OrderID,Date,CustomerID,ProductID,EmpID,City,State,Qty,UnitPrice,Discount,Sales
125,O0126,2026-03-13,C043,P002,E026,Chennai,TN,1,700,10,630

In [108]:
excel[excel['State'].isin(['TN','TS','KA'])]

,OrderID,Date,CustomerID,ProductID,EmpID,City,State,Qty,UnitPrice,Discount,Sales
0,O0001,2026-02-07,C205,P004,E026,Coimbatore,TN,1,15000,0,15000
1,O0002,2026-03-15,C172,P002,E017,Hyderabad,TS,7,700,0,4900
3,O0004,2026-05-28,C125,P002,E085,Bangalore,KA,9,700,10,5670
4,O0005,2026-05-08,C160,P005,E053,Chennai,TN,9,18000,5,153900
6,O0007,2026-02-23,C065,P002,E048,Chennai,TN,2,700,10,1260
...,...,...,...,...,...,...,...,...,...,...,...
494,O0495,2026-02-05,C137,P005,E015,Bangalore,KA,1,18000,15,15300
495,O0496,2026-01-12,C201,P004,E058,Chennai,TN,3,15000,15,38250
497,O0498,2026-01-17,C199,P004,E058,Hyderabad,TS,6,15000,10,81000
498,O0499,2026-03-15,C076,P005,E028,Chennai,TN,8,18000,5,136800
499,O0500,2026-06-15,C218,P002,E082,Hyderabad,TS,1,700,10,630

In [110]:
print(excel.to_string())

    OrderID        Date CustomerID ProductID EmpID        City State  Qty  UnitPrice  Discount   Sales
0     O0001  2026-02-07       C205      P004  E026  Coimbatore    TN    1      15000         0   15000
1     O0002  2026-03-15       C172      P002  E017   Hyderabad    TS    7        700         0    4900
2     O0003  2026-03-15       C042      P004  E096        Pune    MH    2      15000        10   27000
3     O0004  2026-05-28       C125      P002  E085   Bangalore    KA    9        700        10    5670
4     O0005  2026-05-08       C160      P005  E053     Chennai    TN    9      18000         5  153900
5     O0006  2026-01-23       C177      P003  E065        Pune    MH    3       1200        15    3060
6     O0007  2026-02-23       C065      P002  E048     Chennai    TN    2        700        10    1260
7     O0008  2026-01-16       C032      P001  E030   Hyderabad    TS    8      55000        10  396000
8     O0009  2026-03-01       C176      P002  E043   Bangalore    KA    8        700        10    5040
9     O0010  2026-01-19       C213      P005  E044        Pune    MH    9      18000         5  153900
10    O0011  2026-03-17       C189      P005  E081        Pune    MH    5      18000         5   85500
11    O0012  2026-06-07       C121      P002  E049        Pune    MH   10        700        10    6300
12    O0013  2026-04-23       C218      P004  E085  Coimbatore    TN    4      15000         5   57000
13    O0014  2026-02-04       C229      P003  E021   Bangalore    KA    3       1200        10    3240
14    O0015  2026-02-13       C138      P005  E087        Pune    MH    2      18000         0   36000
15    O0016  2026-04-16       C059      P005  E077   Bangalore    KA    5      18000        10   81000
16    O0017  2026-06-15       C016      P003  E063        Pune    MH    5       1200         0    6000
17    O0018  2026-03-18       C226      P003  E100   Bangalore    KA    8       1200        10    8640
18    O0019  2026-05-16       C023      P005  E097     Chennai    TN    1      18000         5   17100
19    O0020  2026-05-03       C022      P001  E097   Hyderabad    TS    7      55000         5  365750
20    O0021  2026-06-28       C167      P003  E073  Coimbatore    TN   10       1200        15   10200
21    O0022  2026-01-03       C159      P002  E040     Chennai    TN    8        700         0    5600
22    O0023  2026-05-16       C049      P005  E032   Bangalore    KA   10      18000        10  162000
23    O0024  2026-01-03       C190      P001  E074     Chennai    TN    4      55000         5  209000
24    O0025  2026-06-13       C091      P004  E095   Hyderabad    TS    3      15000        15   38250
25    O0026  2026-04-15       C090      P001  E018   Hyderabad    TS   10      55000         5  522500
26    O0027  2026-05-07       C094      P005  E073        Pune    MH   10      18000         5  171000
27    O0028  2026-02-27       C126      P001  E048   Hyderabad    TS    1      55000        15   46750
28    O0029  2026-03-16       C068      P004  E023   Bangalore    KA   10      15000        10  135000
29    O0030  2026-05-30       C142      P005  E056  Coimbatore    TN    5      18000         0   90000
30    O0031  2026-01-26       C014      P002  E091   Hyderabad    TS    6        700         5    3990
31    O0032  2026-02-04       C142      P004  E015   Hyderabad    TS    7      15000        10   94500
32    O0033  2026-04-01       C019      P005  E024  Coimbatore    TN    3      18000        10   48600
33    O0034  2026-03-29       C015      P005  E075   Bangalore    KA    9      18000        15  137700
34    O0035  2026-02-24       C268      P003  E023  Coimbatore    TN   10       1200        15   10200
35    O0036  2026-03-28       C171      P004  E099   Hyderabad    TS    9      15000         5  128250
36    O0037  2026-04-24       C052      P001  E026   Bangalore    KA    9      55000         0  495000
37    O0038  2026-02-22       C292      P001  E084        Pune    MH   10      55000        10  495000
38    O0039  2026-03-16       C001      P002  E046        Pune    MH    5        700        10    3150
39    O0040  2026-02-20       C046      P005  E012   Bangalore    KA    7      18000         0  126000
40    O0041  2026-03-08       C124      P001  E018   Bangalore    KA    4      55000         5  209000
41    O0042  2026-04-26       C251      P005  E008     Chennai    TN   10      18000        10  162000
42    O0043  2026-01-25       C025      P002  E072  Coimbatore    TN    3        700        10    1890
43    O0044  2026-04-16       C018      P003  E048        Pune    MH   10       1200         0   12000
44    O0045  2026-02-20       C009      P005  E014   Bangalore    KA    6      18000         5  102600
45    O0046  2026-06-20       C234      P004  E071        Pune    MH    9      15000         0  135000
46    O0047  2026-01-14       C159      P001  E092   Hyderabad    TS   10      55000         5  522500
47    O0048  2026-05-17       C060      P002  E093     Chennai    TN    8        700        15    4760
48    O0049  2026-02-24       C262      P005  E047  Coimbatore    TN    4      18000         0   72000
49    O0050  2026-02-07       C055      P002  E053   Hyderabad    TS    2        700        10    1260
50    O0051  2026-04-20       C224      P002  E085   Hyderabad    TS    2        700         0    1400
51    O0052  2026-03-31       C250      P002  E020   Hyderabad    TS   10        700         5    6650
52    O0053  2026-03-25       C139      P004  E037        Pune    MH    9      15000         0  135000
53    O0054  2026-06-01       C232      P004  E074   Hyderabad    TS    2      15000        15   25500
54    O0055  2026-01-08       C200      P001  E037   Hyderabad    TS    9      55000         5  470250
55    O0056  2026-04-29       C183      P004  E012        Pune    MH   10      15000         0  150000
56    O0057  2026-04-20       C093      P002  E019        Pune    MH    8        700         5    5320
57    O0058  2026-06-08       C203      P005  E097   Bangalore    KA    1      18000         0   18000
58    O0059  2026-05-03       C183      P002  E055  Coimbatore    TN    6        700        10    3780
59    O0060  2026-06-20       C082      P005  E001     Chennai    TN    7      18000         0  126000
60    O0061  2026-05-24       C215      P001  E033   Hyderabad    TS    6      55000         0  330000
61    O0062  2026-01-24       C279      P004  E057   Hyderabad    TS    1      15000         0   15000
62    O0063  2026-03-25       C174      P004  E089   Bangalore    KA    4      15000        10   54000
63    O0064  2026-03-16       C096      P004  E058   Bangalore    KA    7      15000         0  105000
64    O0065  2026-04-02       C002      P005  E032     Chennai    TN    6      18000        10   97200
65    O0066  2026-06-05       C174      P002  E002     Chennai    TN    5        700        10    3150
66    O0067  2026-06-04       C166      P002  E016        Pune    MH    2        700         5    1330
67    O0068  2026-02-11       C123      P004  E074     Chennai    TN    4      15000        10   54000
68    O0069  2026-03-09       C087      P002  E066   Hyderabad    TS    7        700         0    4900
69    O0070  2026-06-26       C019      P005  E099   Hyderabad    TS    7      18000         5  119700
70    O0071  2026-01-16       C254      P001  E045  Coimbatore    TN    7      55000         5  365750
71    O0072  2026-05-12       C046      P001  E012  Coimbatore    TN    9      55000        15  420750
72    O0073  2026-01-24       C016      P004  E030     Chennai    TN    1      15000         5   14250
73    O0074  2026-03-22       C041      P004  E087     Chennai    TN    1      15000         5   14250
74    O0075  2026-06-30       C235      P004  E023        Pune    MH    4      15000        10   54000
75    O0076  2026-05-12       C139      P005  E041     Chennai    TN    1      18000         5   17100
76    O0077  2026-06-23       C141      P005  E059   Bangalore    KA    2      18000        15   30600
77    O0078  2026-03-17       C019      P002  E038   Hyderabad    TS    4        700        15    2380
78    O0079  2026-04-07       C225      P003  E048  Coimbatore    TN    9       1200         5   10260
79    O0080  2026-01-22       C007      P005  E060   Bangalore    KA    8      18000        15  122400
80    O0081  2026-05-23       C262      P005  E030        Pune    MH    4      18000        10   64800
81    O0082  2026-03-16       C246      P003  E081   Hyderabad    TS    2       1200        10    2160
82    O0083  2026-01-01       C049      P003  E063     Chennai    TN    2       1200         5    2280
83    O0084  2026-03-17       C213      P001  E068   Bangalore    KA    1      55000         5   52250
84    O0085  2026-04-06       C103      P003  E083     Chennai    TN    1       1200         0    1200
85    O0086  2026-03-15       C184      P001  E059     Chennai    TN    4      55000         0  220000
86    O0087  2026-06-18       C135      P004  E034        Pune    MH    1      15000         5   14250
87    O0088  2026-01-31       C168      P003  E094   Bangalore    KA    2       1200        10    2160
88    O0089  2026-02-13       C195      P001  E079     Chennai    TN    5      55000        10  247500
89    O0090  2026-06-23       C115      P005  E009  Coimbatore    TN    3      18000        10   48600
90    O0091  2026-04-24       C292      P002  E029     Chennai    TN    5        700        10    3150
91    O0092  2026-01-14       C054      P001  E006  Coimbatore    TN    6      55000         0  330000
92    O0093  2026-06-19       C040      P004  E090   Hyderabad    TS    8      15000        15  102000
93    O0094  2026-03-25       C245      P005  E079   Bangalore    KA    1      18000        15   15300
94    O0095  2026-05-21       C259      P003  E009   Bangalore    KA    9       1200         0   10800
95    O0096  2026-06-22       C179      P002  E052   Hyderabad    TS    5        700         5    3325
96    O0097  2026-05-04       C017      P004  E057   Hyderabad    TS    6      15000        15   76500
97    O0098  2026-04-03       C257      P001  E066   Hyderabad    TS    8      55000         5  418000
98    O0099  2026-05-02       C294      P005  E060  Coimbatore    TN    9      18000         0  162000
99    O0100  2026-04-25       C171      P001  E016   Hyderabad    TS    3      55000        15  140250
100   O0101  2026-02-21       C174      P005  E065        Pune    MH    4      18000         5   68400
101   O0102  2026-02-02       C231      P003  E028   Hyderabad    TS    8       1200        15    8160
102   O0103  2026-06-09       C052      P003  E094   Bangalore    KA    8       1200        15    8160
103   O0104  2026-02-10       C055      P005  E052        Pune    MH    7      18000         5  119700
104   O0105  2026-04-06       C164      P004  E044     Chennai    TN    9      15000         5  128250
105   O0106  2026-04-20       C006      P002  E015        Pune    MH    8        700        15    4760
106   O0107  2026-05-18       C156      P001  E059     Chennai    TN    5      55000        15  233750
107   O0108  2026-04-13       C258      P001  E002   Hyderabad    TS    5      55000        15  233750
108   O0109  2026-05-03       C126      P004  E083   Bangalore    KA    6      15000        15   76500
109   O0110  2026-06-18       C266      P002  E055        Pune    MH    5        700        15    2975
110   O0111  2026-02-05       C295      P001  E054        Pune    MH    8      55000        15  374000
111   O0112  2026-04-26       C149      P004  E044        Pune    MH    4      15000         0   60000
112   O0113  2026-05-26       C216      P002  E042     Chennai    TN    8        700        15    4760
113   O0114  2026-04-17       C161      P002  E049     Chennai    TN    8        700        10    5040
114   O0115  2026-04-17       C090      P004  E030        Pune    MH    2      15000        15   25500
115   O0116  2026-02-10       C230      P004  E030   Hyderabad    TS    9      15000        10  121500
116   O0117  2026-05-15       C228      P002  E050  Coimbatore    TN    3        700        15    1785
117   O0118  2026-02-24       C010      P002  E054  Coimbatore    TN   10        700        15    5950
118   O0119  2026-04-02       C233      P005  E086   Hyderabad    TS    3      18000         5   51300
119   O0120  2026-01-31       C140      P005  E042     Chennai    TN    1      18000         5   17100
120   O0121  2026-03-21       C132      P003  E098     Chennai    TN    1       1200        15    1020
121   O0122  2026-05-05       C219      P004  E075   Bangalore    KA    9      15000         0  135000
122   O0123  2026-03-19       C054      P003  E063        Pune    MH   10       1200        10   10800
123   O0124  2026-01-21       C081      P002  E090     Chennai    TN    3        700        10    1890
124   O0125  2026-04-19       C010      P005  E020  Coimbatore    TN    1      18000        15   15300
125   O0126  2026-03-13       C043      P002  E026     Chennai    TN    1        700        10     630
126   O0127  2026-01-23       C243      P002  E056   Hyderabad    TS    2        700         0    1400
127   O0128  2026-06-24       C083      P003  E019   Hyderabad    TS    3       1200         0    3600
128   O0129  2026-01-10       C283      P005  E042        Pune    MH    2      18000         5   34200
129   O0130  2026-01-24       C190      P002  E035   Bangalore    KA    9        700         0    6300
130   O0131  2026-06-20       C213      P001  E034        Pune    MH    4      55000         0  220000
131   O0132  2026-06-15       C263      P004  E014   Hyderabad    TS    7      15000         0  105000
132   O0133  2026-04-25       C275      P005  E090        Pune    MH    8      18000         0  144000
133   O0134  2026-01-07       C285      P002  E054   Bangalore    KA    2        700        10    1260
134   O0135  2026-03-18       C249      P001  E048     Chennai    TN   10      55000        15  467500
135   O0136  2026-06-06       C170      P005  E051     Chennai    TN    6      18000         0  108000
136   O0137  2026-04-19       C198      P005  E030  Coimbatore    TN    5      18000        15   76500
137   O0138  2026-03-26       C002      P002  E037     Chennai    TN   10        700         0    7000
138   O0139  2026-03-02       C219      P001  E016   Bangalore    KA    3      55000        15  140250
139   O0140  2026-04-05       C181      P004  E018        Pune    MH    3      15000         0   45000
140   O0141  2026-03-23       C161      P003  E013        Pune    MH    5       1200        15    5100
141   O0142  2026-03-13       C222      P005  E054  Coimbatore    TN    4      18000        15   61200
142   O0143  2026-04-30       C059      P003  E069   Hyderabad    TS   10       1200         5   11400
143   O0144  2026-05-15       C008      P003  E031   Hyderabad    TS    7       1200        10    7560
144   O0145  2026-04-24       C052      P001  E011   Hyderabad    TS    7      55000        10  346500
145   O0146  2026-02-25       C210      P004  E005        Pune    MH    1      15000        10   13500
146   O0147  2026-02-08       C277      P003  E092   Bangalore    KA   10       1200         0   12000
147   O0148  2026-01-15       C010      P002  E003  Coimbatore    TN    5        700         5    3325
148   O0149  2026-06-03       C228      P003  E077   Bangalore    KA    2       1200        15    2040
149   O0150  2026-03-11       C141      P001  E036     Chennai    TN    8      55000         0  440000
150   O0151  2026-01-01       C034      P003  E008  Coimbatore    TN    7       1200        15    7140
151   O0152  2026-06-28       C247      P002  E090     Chennai    TN    3        700        15    1785
152   O0153  2026-04-08       C066      P001  E071   Hyderabad    TS    9      55000         0  495000
153   O0154  2026-05-17       C014      P004  E038        Pune    MH    3      15000         0   45000
154   O0155  2026-06-12       C284      P003  E025  Coimbatore    TN    6       1200         5    6840
155   O0156  2026-03-15       C039      P004  E067  Coimbatore    TN   10      15000        10  135000
156   O0157  2026-06-10       C003      P001  E095     Chennai    TN    9      55000        15  420750
157   O0158  2026-06-23       C018      P003  E025        Pune    MH    2       1200        10    2160
158   O0159  2026-05-31       C187      P005  E019     Chennai    TN    1      18000         5   17100
159   O0160  2026-02-04       C266      P002  E086   Hyderabad    TS    2        700        10    1260
160   O0161  2026-03-10       C052      P004  E053  Coimbatore    TN    4      15000        10   54000
161   O0162  2026-02-07       C035      P005  E088     Chennai    TN   10      18000        15  153000
162   O0163  2026-06-16       C071      P001  E037        Pune    MH   10      55000        10  495000
163   O0164  2026-02-18       C291      P002  E006     Chennai    TN    4        700         5    2660
164   O0165  2026-04-01       C012      P004  E089  Coimbatore    TN    8      15000         5  114000
165   O0166  2026-02-24       C006      P003  E099  Coimbatore    TN    2       1200        10    2160
166   O0167  2026-05-14       C055      P005  E084   Bangalore    KA    1      18000        10   16200
167   O0168  2026-04-29       C143      P003  E061   Bangalore    KA   10       1200        10   10800
168   O0169  2026-04-16       C034      P001  E021        Pune    MH    2      55000         5  104500
169   O0170  2026-04-10       C077      P005  E085   Hyderabad    TS    4      18000        10   64800
170   O0171  2026-02-06       C103      P003  E001  Coimbatore    TN    2       1200        10    2160
171   O0172  2026-05-11       C127      P001  E022   Bangalore    KA   10      55000         5  522500
172   O0173  2026-03-22       C032      P001  E085   Bangalore    KA    5      55000        15  233750
173   O0174  2026-06-26       C214      P005  E043  Coimbatore    TN    9      18000        10  145800
174   O0175  2026-03-30       C138      P002  E018   Hyderabad    TS    2        700         0    1400
175   O0176  2026-04-17       C209      P004  E071  Coimbatore    TN    7      15000         0  105000
176   O0177  2026-03-08       C182      P002  E008  Coimbatore    TN    5        700        10    3150
177   O0178  2026-03-16       C253      P004  E020   Bangalore    KA    2      15000         0   30000
178   O0179  2026-05-20       C029      P002  E039  Coimbatore    TN    8        700         0    5600
179   O0180  2026-06-09       C161      P001  E040   Hyderabad    TS    8      55000         0  440000
180   O0181  2026-01-28       C176      P004  E082        Pune    MH    4      15000         0   60000
181   O0182  2026-05-17       C011      P004  E060        Pune    MH    1      15000         0   15000
182   O0183  2026-06-14       C257      P001  E007   Bangalore    KA   10      55000         0  550000
183   O0184  2026-01-23       C207      P003  E065        Pune    MH    7       1200        15    7140
184   O0185  2026-02-11       C039      P003  E055     Chennai    TN    4       1200         5    4560
185   O0186  2026-05-05       C124      P005  E081   Bangalore    KA    2      18000        10   32400
186   O0187  2026-04-29       C075      P002  E009   Bangalore    KA    3        700        15    1785
187   O0188  2026-01-05       C217      P003  E047  Coimbatore    TN    6       1200        15    6120
188   O0189  2026-01-19       C102      P003  E055   Bangalore    KA   10       1200         0   12000
189   O0190  2026-06-07       C023      P001  E003  Coimbatore    TN    7      55000        15  327250
190   O0191  2026-03-21       C269      P005  E100  Coimbatore    TN    4      18000         0   72000
191   O0192  2026-02-13       C137      P003  E002   Bangalore    KA    9       1200        15    9180
192   O0193  2026-04-26       C185      P005  E019   Bangalore    KA    6      18000         0  108000

In [114]:
excel[(excel['State']=='TN') & (excel['Discount']>5)].str.

,OrderID,Date,CustomerID,ProductID,EmpID,City,State,Qty,UnitPrice,Discount,Sales
6,O0007,2026-02-23,C065,P002,E048,Chennai,TN,2,700,10,1260
20,O0021,2026-06-28,C167,P003,E073,Coimbatore,TN,10,1200,15,10200
32,O0033,2026-04-01,C019,P005,E024,Coimbatore,TN,3,18000,10,48600
34,O0035,2026-02-24,C268,P003,E023,Coimbatore,TN,10,1200,15,10200
41,O0042,2026-04-26,C251,P005,E008,Chennai,TN,10,18000,10,162000
...,...,...,...,...,...,...,...,...,...,...,...
468,O0469,2026-02-15,C061,P002,E011,Chennai,TN,6,700,10,3780
473,O0474,2026-05-09,C282,P005,E084,Coimbatore,TN,2,18000,15,30600
476,O0477,2026-02-27,C200,P004,E035,Coimbatore,TN,6,15000,10,81000
486,O0487,2026-06-03,C293,P001,E089,Coimbatore,TN,10,55000,15,467500
495,O0496,2026-01-12,C201,P004,E058,Chennai,TN,3,15000,15,38250

AttributeError: 'DataFrame' object has no attribute 'str'

In [119]:
file.sort_values('Age').head(50)

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
14,15,Priya Reddy,0.0,M,HR,BANGALORE,priya.reddy15@company.com,Part-Time,28000,17-12-2018,0.0,-5.0
76,77,Meena Joseph,0.0,Male,Marketing,BANGALORE,meena.joseph77@gmail.com,Contract,63000,04-12-2022,6.0,-5.0
128,129,Gokul Das,0.0,male,it,Chennai,gokul.das129@company.com,Full-Time,78000,16-12-2025,NaN,75.0
173,174,Rahul Kumar,0.0,Male,it,Chennai,invalid-email,full time,58000,21-04-2025,6.0,95.0
197,198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,16-03-2019,6.0,105.0
114,115,Karthik Iyer,17.0,male,SALES,chennai,karthik.iyer115 @yahoo.com,full time,103000,26-12-2025,6.0,NaN
99,100,Manoj Kumar,17.0,female,Marketing,Bangalore,manoj.kumar100@gmail.com,contract,73000,19-03-2026,NaN,85.0
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,27-01-2018,4.0,100.0
32,33,Kavya Nair,21.0,Male,finance,Hyderabad,kavya.nair33@company.com,NaN,33000,05-11-2018,3.5,-5.0
39,40,Priya Das,21.0,Male,Operations,Mumbai,priya.das40@company.com,Full-Time,98000,15-01-2024,3.5,100.0
13,14,Nisha Nair,21.0,female,HR,Chennai,nisha.nair14@yahoo.com,NaN,113000,20-08-2021,5.0,90.0
29,30,Swetha Nair,21.0,male,Finance,Bangalore,swetha.nair30@yahoo.com,Full-Time,NaN,21-03-2024,2.0,-5.0
52,53,Kavya Rao,22.0,M,NaN,chennai,kavya.rao53@company.com,NaN,78000,08-10-2021,0.0,85.0
78,79,Gokul Joseph,22.0,NaN,Finance,Chennai,gokul.joseph79@company.com,Part time,NaN,08-01-2021,0.0,95.0
110,111,Divya Sharma,22.0,female,SALES,Mumbai,divya.sharma111@yahoo.com,Full-Time,38000,02-03-2018,3.0,95.0
103,104,Anitha Rao,22.0,Female,Sales,Chennai,anitha.rao104@yahoo.com,contract,113000,18-04-2024,0.0,95.0
108,109,Vijay Joseph,22.0,F,SALES,Hyderabad,vijay.joseph109@gmail.com,Full-Time,23000,28-09-2021,6.0,90.0
148,149,Pooja Reddy,22.0,M,Finance,Delhi,pooja.reddy149@company.com,Full-Time,68000,10-02-2019,5.0,105.0
55,56,Rahul Rao,22.0,Female,Sales,Delhi,rahul.rao56@gmail.com,NaN,0,19-01-2024,1.0,75.0
53,E054,Swetha Nair,22.0,Male,HR,Chennai,swetha.nair54@company.com,Part-Time,78000,21-08-2024,0.0,85.0
156,157,Meena Reddy,23.0,Male,finance,Pune,meena.reddy157@yahoo.com,NaN,48000,21-06-2018,6.0,105.0
125,126,Hari Iyer,23.0,F,IT,Chennai,hari.iyer126@company.com,Contract,53000,07-06-2022,4.0,85.0
142,143,Nisha Nair,23.0,Male,SALES,Hyderabad,nisha.nair143@company.com,Part-Time,NaN,11-10-2021,3.0,85.0
70,71,Ravi Patel,24.0,NaN,it,Bangalore,ravi.patel71@gmail.com,Full-Time,58000,11-05-2023,1.0,85.0
6,7,Vijay Iyer,25.0,M,Sales,Hyderbad,vijay.iyer7@gmail.com,full time,113000,13-02-2025,NaN,95.0
133,134,Karthik Rao,25.0,Male,Marketing,Pune,karthik.rao134@company.com,Contract,93000,17-12-2022,6.0,80.0
162,163,Priya Patel,25.0,Male,it,Delhi,priya.patel163@yahoo.com,Part time,53000,27-03-2025,3.0,105.0
27,28,Manoj Singh,25.0,Female,HR,Chennai,manoj.singh28@company.com,Part time,18000,21-02-2023,4.0,-5.0
5,6,Anitha Iyer,26.0,female,Human Resources,Pune,anitha.iyer6@yahoo.com,Part-Time,53000,18-02-2019,3.5,100.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,15-04-2021,2.0,75.0
117,118,Rahul Sharma,26.0,Male,Finance,Delhi,rahul.sharma118@company.com,Part time,83000,31-01-2019,6.0,-5.0
77,78,Deepa Rao,26.0,male,SALES,Delhi,deepa.rao78@yahoo.com,Full-Time,113000,13-06-2018,2.0,90.0
73,74,Vijay Iyer,26.0,M,HR,Hyderbad,vijay.iyer74@gmail.com,Full-Time,43000,09-09-2020,NaN,105.0
159,160,Rahul Das,26.0,female,Marketing,Hyderbad,rahul.das160@gmail.com,Full-Time,83000,03-10-2024,2.0,100.0
43,44,Deepa Patel,26.0,Female,Operations,Chennai,deepa.patel44@company.com,NaN,63000,13-10-2023,4.0,95.0
176,177,Hari Nair,27.0,NaN,Marketing,Bangalore,hari.nair177@yahoo.com,Part-Time,68000,17-09-2020,3.0,80.0
21,22,Manoj Nair,27.0,F,HR,Chennai,manoj.nair22@company.com,Part-Time,23000,25-04-2025,NaN,105.0
194,195,Anitha Kumar,27.0,M,HR,BANGALORE,anitha.kumar195@company.com,Full-Time,83000,14-09-2021,6.0,85.0
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,28-10-2019,3.5,95.0
102,103,Suresh Nair,28.0,Male,SALES,Pune,suresh.nair103@company.com,NaN,88000,18-02-2022,3.5,80.0
81,82,Suresh Singh,28.0,Male,Human Resources,Hyderbad,suresh.singh82@gmail.com,Full-Time,78000,10-09-2023,4.0,-5.0
16,17,hari rao,28.0,F,IT,Delhi,hari.rao17@gmail.com,Part time,53000,09-07-2020,4.0,75.0
33,34,karthik das,29.0,F,Operations,Chennai,karthik.das34@yahoo.com,contract,23000,16-06-2021,4.0,80.0
69,70,Nisha Iyer,29.0,male,IT,Bangalore,nisha.iyer70@yahoo.com,full time,118000,11-06-2026,0.0,105.0
168,169,Manoj Nair,29.0,NaN,it,Pune,manoj.nair169@gmail.com,Part time,113000,20-12-2018,NaN,NaN
169,170,gokul sharma,29.0,female,Human Resources,BANGALORE,gokul.sharma170@gmail.com,Part-Time,68000,16-03-2025,6.0,85.0
104,105,Kavya Sharma,29.0,Female,HR,BANGALORE,kavya.sharma105@yahoo.com,Part-Time,23000,02-06-2018,6.0,85.0
49,50,Rahul Patel,30.0,Female,Sales,Hyderabad,rahul.patel50@company.com,full time,53000,18-04-2022,NaN,100.0
44,45,Anitha Reddy,30.0,Female,SALES,BANGALORE,anitha.reddy45@gmail.com,full time,18000,09-07-2018,NaN,90.0
139,140,Rahul Joseph,30.0,Female,Finance,chennai,rahul.joseph140@company.com,Contract,73000,24-06-2021,6.0,NaN

In [126]:
file.sort_values(['Salary','Age'],ascending=False).head(20)

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
24,25,Priya Joseph,51.0,Female,finance,Chennai,priya.joseph25@gmail.com,NaN,98000,16-12-2023,3.0,80.0
112,113,Gokul Sharma,49.0,male,finance,Chennai,gokul.sharma113@company.com,full time,98000,26-06-2020,1.0,75.0
111,112,Priya Patel,47.0,NaN,Human Resources,Bangalore,priya.patel112@company.com,NaN,98000,11-04-2019,3.5,-5.0
12,13,Suresh Nair,32.0,F,finance,Pune,suresh.nair13@company.com,Part-Time,98000,12-03-2019,3.5,85.0
39,40,Priya Das,21.0,Male,Operations,Mumbai,priya.das40@company.com,Full-Time,98000,15-01-2024,3.5,100.0
141,142,Divya Reddy,42.0,Female,Finance,Hyderabad,divya.reddy142@gmail.com,Contract,93000,26-02-2020,2.0,-5.0
183,184,Priya Patel,42.0,M,SALES,Hyderabad,priya.patel184 @yahoo.com,Contract,93000,29-10-2023,3.5,85.0
144,145,Nisha Reddy,40.0,NaN,Human Resources,Chennai,invalid-email,NaN,93000,05-03-2020,5.0,NaN
179,180,Priya Kumar,39.0,Male,Marketing,BANGALORE,priya.kumar180@company.com,NaN,93000,13-09-2024,2.0,NaN
164,165,Sneha Kumar,32.0,male,HR,Hyderbad,sneha.kumar165@yahoo.com,NaN,93000,22-10-2023,5.0,105.0
133,134,Karthik Rao,25.0,Male,Marketing,Pune,karthik.rao134@company.com,Contract,93000,17-12-2022,6.0,80.0
94,95,Swetha Das,NaN,male,Human Resources,Mumbai,swetha.das95@gmail.com,full time,93000,16-07-2024,5.0,75.0
181,182,Rahul Das,53.0,Female,SALES,Chennai,rahul.das182@yahoo.com,Part-Time,88000,02-03-2024,2.0,NaN
19,20,Pooja Das,47.0,Male,IT,Bangalore,pooja.das20@gmail.com,contract,88000,06-03-2026,3.5,80.0
48,49,Deepa Reddy,38.0,male,Sales,Pune,deepa.reddy49@company.com,Contract,88000,14-11-2018,3.5,-5.0
62,63,Suresh Rao,36.0,Male,Operations,chennai,suresh.rao63@company.com,full time,88000,23-05-2024,3.5,85.0
102,103,Suresh Nair,28.0,Male,SALES,Pune,suresh.nair103@company.com,NaN,88000,18-02-2022,3.5,80.0
38,39,Priya Sharma,65.0,Female,it,Delhi,priya.sharma39@company.com,full time,83000,16-11-2021,4.0,95.0
122,123,Hari Reddy,45.0,male,Operations,Hyderabad,hari.reddy123@yahoo.com,contract,83000,02-02-2023,3.5,80.0
116,117,Kavya Sharma,41.0,M,Operations,Pune,kavya.sharma117@company.com,contract,83000,04-07-2021,0.0,80.0