## Pandas

In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\Admin\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Admin\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [8]:
# print(pd.__version__)

pip show pandas

SyntaxError: invalid syntax (3967507037.py, line 3)

In [20]:
d = pd.Series([10,20,30,40,50])
print(d)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [24]:

print(data.loc[1])

KeyError: 1

In [25]:
data = pd.Series([10,20,30,40,50],index=["tamil","english","math","s","ss"])
print(data)

tamil      10
english    20
math       30
s          40
ss         50
dtype: int64

In [13]:
 d =data.loc["tamil"]

In [14]:
print(d)

10

In [26]:
print(data.loc["s"])

40

In [27]:
print(data.iloc[1])

20

In [31]:
print(data["tamil"])

10

In [32]:
data["m"]=22

In [33]:
print(data)

tamil      10
english    20
math       30
s          40
ss         50
m          22
dtype: int64

In [52]:
students = {
    "name" : ["lathika","sridher","lingesh"],
    "age":[23,24,25],
    "subject":["DA","genai","DE"]
}

In [53]:
print(students)

{'name': ['lathika', 'sridher', 'lingesh'], 'age': [23, 24, 25], 'subject': ['DA', 'genai', 'DE']}

In [54]:
data = pd.DataFrame(students)

In [55]:
print(data)

      name  age subject
0  lathika   23      DA
1  sridher   24   genai
2  lingesh   25      DE

In [40]:
print(data.loc[0])

name       lathika
age             23
subject         DA
Name: 0, dtype: object

In [47]:
students = pd.DataFrame([{"name":"bala","age":20,"subject":"DS"}],index=[3])

In [48]:
print(data)

   name  age subject
3  bala   20      DS

In [49]:
d=pd.DataFrame(students)

In [50]:
print(d)

   name  age subject
3  bala   20      DS

In [56]:
df = pd.concat([data,d])

In [57]:
print(df)

      name  age subject
0  lathika   23      DA
1  sridher   24   genai
2  lingesh   25      DE
3     bala   20      DS

In [79]:
 d=df.loc[(df["age"]<25) | (df["age"]>22)]

In [81]:
 d=df.loc[ ~ (df["age"]<25).str.]

In [82]:
print(d)

      name  age subject
2  lingesh   25      DE

In [83]:
df["name"].str.endswith("a")

0     True
1    False
2    False
3     True
Name: name, dtype: bool

In [85]:
read = pd.read_csv("C:\\Users\\Admin\\OneDrive\\Documents\\CourseNotes\\Data.csv")

In [86]:
print(read)

    id    name  age department  salary
0  101    Ravi   25         IT   35000
1  102  Anitha   28         HR   40000
2  103   Kumar   30    Finance   45000
3  104   Divya   26         IT   38000

In [92]:
read_excel = pd.read_excel('C:\\Users\\Admin\\OneDrive\\Documents\\CourseNotes\\DA\\Excel_\\Excel_Data_Cleaning_Practice_500_Rows.xlsx')
print(read_excel)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Admin\\OneDrive\\Documents\\CourseNotes\\DA\\Excel_\\Excel_Data_Cleaning_Practice_500_Rows.xlsx'

In [93]:
read.head()

    id    name  age department  salary
0  101    Ravi   25         IT   35000
1  102  Anitha   28         HR   40000
2  103   Kumar   30    Finance   45000
3  104   Divya   26         IT   38000

In [94]:
read.head(2)

    id    name  age department  salary
0  101    Ravi   25         IT   35000
1  102  Anitha   28         HR   40000

In [98]:
read.tail(2)

    id   name  age department  salary
2  103  Kumar   30    Finance   45000
3  104  Divya   26         IT   38000

In [1]:
import pandas as pd

In [2]:
students = {
    "name" : ["lathika","sridher","lingesh"],
    "age":[23,24,25],
    "subject":["DA","genai","DE"]
}

In [3]:
df = pd.DataFrame(students)

In [6]:
df

      name  age subject
0  lathika   23      DA
1  sridher   24   genai
2  lingesh   25      DE

In [11]:
print(df[df["age"]>=30])

Empty DataFrame
Columns: [name, age, subject]
Index: []

In [17]:
df[~ df["age"]<=20]

      name  age subject
0  lathika   23      DA
1  sridher   24   genai
2  lingesh   25      DE

In [15]:
df[(df["age"]>=20) | (df["age"]<=23)]

      name  age subject
0  lathika   23      DA
1  sridher   24   genai
2  lingesh   25      DE

In [18]:
df[df["subject"].isin(["DA","DE"])]

      name  age subject
0  lathika   23      DA
2  lingesh   25      DE

In [20]:
df.sort_values("name")

      name  age subject
0  lathika   23      DA
2  lingesh   25      DE
1  sridher   24   genai

In [62]:
data=pd.read_csv("C:\\Users\\Admin\\OneDrive\\Documents\\CourseNotes\\employee_data_cleaning_practice_200_rows.csv")

In [22]:
data

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,03-07-2020,NaN,75.0
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,01-09-2023,6.0,NaN
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,27-01-2018,4.0,100.0
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,10-01-2022,0.0,-5.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,15-04-2021,2.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,27-03-2020,2.0,90.0
196,197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,22-12-2019,5.0,75.0
197,198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,16-03-2019,6.0,105.0
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,28-10-2019,3.5,95.0
199,200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,01-03-2025,NaN,80.0

In [24]:
print(data.to_string())

    Employee_ID    Employee_Name   Age  Gender         Department        City                         Email Employment_Type     Salary Joining_Date  Performance_Score  Attendance_Percentage
0             1      Sneha Kumar  38.0  Female            finance   Bangalore        sneha.kumar1@gmail.com       Part time      53000   03-07-2020                NaN                   75.0
1             2      Arun Sharma  34.0       F            finance     Chennai      arun.sharma2@company.com        contract      53000   01-09-2023                6.0                    NaN
2             3       Anitha Rao  17.0    male         Operations     chennai         anitha.rao3@gmail.com       Part-Time      58000   27-01-2018                4.0                  100.0
3             4     Sneha Sharma  45.0    Male          Marketing     Chennai       sneha.sharma4@yahoo.com        contract      33000   10-01-2022                0.0                   -5.0
4             5        Sneha Das  26.0       F         Operations     Chennai        sneha.das5@company.com        contract     103000   15-04-2021                2.0                   75.0
5             6      Anitha Iyer  26.0  female   Human Resources         Pune        anitha.iyer6@yahoo.com       Part-Time      53000   18-02-2019                3.5                  100.0
6             7       Vijay Iyer  25.0       M              Sales    Hyderbad         vijay.iyer7@gmail.com       full time     113000   13-02-2025                NaN                   95.0
7             8      Nisha Reddy  41.0    male                 it       Delhi        nisha.reddy8@gmail.com       Full-Time      23000   27-07-2020                4.0                  100.0
8             9        Vijay Rao  46.0       F            Finance        Pune          vijay.rao9@gmail.com        contract     118000   23-02-2023                6.0                   -5.0
9            10    Suresh Joseph  48.0     NaN            Finance      Mumbai     suresh.joseph10@yahoo.com       Full-Time     108000   24-06-2022                1.0                   80.0
10           11    Karthik Patel  48.0     NaN              SALES     chennai     karthik.patel11@yahoo.com       Part time     113000   18-09-2018                5.0                   -5.0
11           12      Arun Sharma  55.0   Male           Marketing   Bangalore       arun.sharma12@yahoo.com       Part-Time      58000   10-03-2025                0.0                   75.0
12           13      Suresh Nair  32.0       F            finance        Pune     suresh.nair13@company.com       Part-Time      98000   12-03-2019                3.5                   85.0
13           14       Nisha Nair  21.0  female                 HR     Chennai        nisha.nair14@yahoo.com             NaN     113000   20-08-2021                5.0                   90.0
14           15      Priya Reddy   0.0       M                 HR  BANGALORE      priya.reddy15@company.com       Part-Time      28000   17-12-2018                0.0                   -5.0
15           16       Divya Iyer  54.0    male              Sales    Hyderbad        divya.iyer16@gmail.com       full time     113000   30-09-2022                3.5                  105.0
16           17        hari rao   28.0       F                 IT       Delhi          hari.rao17@gmail.com       Part time      53000   09-07-2020                4.0                   75.0
17           18      Rahul Kumar  35.0       F            finance   Bangalore       rahul.kumar18@yahoo.com        Contract      28000   09-05-2018                0.0                   90.0
18           19      Nisha Patel   NaN       F                 it  BANGALORE        nisha.patel19@gmail.com       Full-Time     108000   21-04-2023                2.0                    NaN
19           20        Pooja Das  47.0   Male                  IT   Bangalore         pooja.das20@gmail.com        contract      88000   06-03-2026                3.5                   80.0
20           21     Anitha Reddy  33.0    male            Finance     chennai      anitha.reddy21@gmail.com       full time     103000   12-01-2023                4.0                   80.0
21           22       Manoj Nair  27.0       F                 HR     Chennai      manoj.nair22@company.com       Part-Time      23000   25-04-2025                NaN                  105.0
22           23      Deepa Reddy  46.0    male                 it     Chennai      deepa.reddy23 @yahoo.com             NaN      23000   06-11-2019                0.0                   95.0
23           24       Kavya Nair  52.0    Male                 IT      Mumbai        kavya.nair24@yahoo.com        contract      38000   17-02-2020                3.5                   75.0
24           25     Priya Joseph  51.0  Female            finance     Chennai      priya.joseph25@gmail.com             NaN      98000   16-12-2023                3.0                   80.0
25           26    Swetha Sharma  36.0    Male              SALES      Mumbai   swetha.sharma26@company.com       Part time      78000   07-05-2019                2.0                    NaN
26         E027     Gokul Joseph  54.0    male              Sales       Delhi      gokul.joseph27@gmail.com       full time      68000   04-12-2020                3.0                   95.0
27           28      Manoj Singh  25.0  Female                 HR     Chennai     manoj.singh28@company.com       Part time      18000   21-02-2023                4.0                   -5.0
28           29     Suresh Patel  43.0     NaN            Finance        Pune                 invalid-email             NaN      28000   27-09-2020                6.0                   95.0
29           30      Swetha Nair  21.0    male            Finance   Bangalore       swetha.nair30@yahoo.com       Full-Time        NaN   21-03-2024                2.0                   -5.0
30           31     Karthik Iyer  39.0    male              Sales       Delhi    karthik.iyer31@company.com       Part time  45000 INR   12-05-2020                0.0                   95.0
31           32     Priya Sharma  48.0    male            Finance       Delhi      priya.sharma32@gmail.com       Part-Time      58000   30-06-2018                0.0                   -5.0
32           33       Kavya Nair  21.0    Male            finance   Hyderabad      kavya.nair33@company.com             NaN      33000   05-11-2018                3.5                   -5.0
33           34     karthik das   29.0       F         Operations     Chennai       karthik.das34@yahoo.com        contract      23000   16-06-2021                4.0                   80.0
34           35       Pooja Nair  47.0       M            Finance      Mumbai        pooja.nair35@gmail.com       full time     113000   28-05-2026                1.0                   85.0
35           36         Ravi Das  36.0    Male                 it   Bangalore        ravi.das36@company.com             NaN      58000   15-10-2019                0.0                   90.0
36           37        Vijay Rao  43.0   Male               Sales     Chennai         vijay.rao37@gmail.com        Contract      63000   21-07-2020                5.0                   80.0
37           38     Suresh Singh   NaN  Female                 IT       Delhi    suresh.singh38@company.com        Contract      78000   15-08-2025                3.0                   95.0
38           39     Priya Sharma  65.0  Female                 it       Delhi    priya.sharma39@company.com       full time      83000   16-11-2021                4.0                   95.0
39           40        Priya Das  21.0   Male          Operations      Mumbai       priya.das40@company.com       Full-Time      98000   15-01-2024                3.5                  100.0
40           41       Sneha Iyer  53.0    male                 it       Delhi        sneha.iyer41@yahoo.com       Part time      63000   06-24-2025                3.0                   90.0
41           42        Kavya Das  32.0    Male            finance     chennai         kavya.das42@yahoo.com        Contract     113000   20-05-2024                5.0                   90.0
42           43     Kavya Joseph  65.0     NaN   Human Resources     Chennai       kavya.joseph43@yahoo.com        contract     118000   12-08-2021                4.0                   -5.0
43           44      Deepa Patel  26.0  Female         Operations     Chennai     deepa.patel44@company.com             NaN      63000   13-10-2023                4.0                   95.0
44           45     Anitha Reddy  30.0  Female              SALES  BANGALORE       anitha.reddy45@gmail.com       full time      18000   09-07-2018                NaN                   90.0
45           46         Ajay Rao  46.0   Male                  HR     Chennai       ajay.rao46 @company.com       Part-Time      53000   28-08-2019                3.0                   -5.0
46           47      Manoj Kumar   NaN  female   Human Resources    Hyderabad       manoj.kumar47@yahoo.com             NaN      53000          NaN                0.0                   -5.0
47           48       Kavya Nair  49.0       F          Marketing  BANGALORE         kavya.nair48@yahoo.com             NaN      43000   05-05-2026                5.0                   -5.0
48           49      Deepa Reddy  38.0    male              Sales        Pune     deepa.reddy49@company.com        Contract      88000   14-11-2018                3.5                   -5.0
49           50      Rahul Patel  30.0  Female              Sales   Hyderabad     rahul.patel50@company.com       full time      53000   18-04-2022                NaN                  100.0
50           51       nisha rao   47.0    Male              SALES     chennai         nisha.rao51@yahoo.com             NaN      23000   27-04-2020                NaN                  105.0
51           52       Arun Singh  40.0       F              SALES    Hyderbad      arun.singh52@company.com       full time      78000   13-09-2022                4.0                   95.0
52           53        Kavya Rao  22.0       M                NaN     chennai       kavya.rao53@company.com             NaN      78000   08-10-2021                0.0                   85.0
53         E054      Swetha Nair  22.0   Male                  HR     Chennai     swetha.nair54@company.com       Part-Time      78000   21-08-2024                0.0                   85.0
54           55       Priya Iyer  45.0   Male          Operations       Delhi        priya.iyer55@yahoo.com        Contract      68000   16-05-2020                NaN                   95.0
55           56        Rahul Rao  22.0  Female              Sales       Delhi         rahul.rao56@gmail.com             NaN          0   19-01-2024                1.0                   75.0
56           57     Anitha Reddy   NaN  Female   Human Resources    Hyderabad      anitha.reddy57@gmail.com       Part time     113000   17-09-2019                4.0                  105.0
57           58     Suresh Singh  31.0    male            Finance   Bangalore                 invalid-email       Full-Time     113000   23-10-2024                1.0                   95.0
58           59        Gokul Das  46.0  Female              Sales     Chennai         gokul.das59@gmail.com        contract     -25000   23-03-2020                5.0                   80.0
59           60      Gokul Kumar  43.0  female                 HR       Delhi     gokul.kumar60@company.com       Full-Time     103000   21-10-2022                NaN                  105.0
60           61        Sneha Das  44.0       M                 it   Hyderabad       sneha.das61@company.com        contract     118000   27-02-2023                6.0                   95.0
61           62      Swetha Nair  51.0  female          Marketing     Chennai     swetha.nair62@company.com             NaN  45000 INR   20-11-2022                4.0                   80.0
62           63       Suresh Rao  36.0    Male         Operations     chennai      suresh.rao63@company.com       full time      88000   23-05-2024                3.5                   85.0
63           64      Deepa Reddy  43.0    Male          Marketing     Chennai       deepa.reddy64@yahoo.com       Part time      58000   26-10-2021                4.0                   80.0
64           65       Anitha Das  52.0     NaN   Human Resources   BANGALORE       anitha.das65@company.com             NaN     103000   11-09-2020                1.0                   80.0
65           66      Meena Reddy  46.0     NaN         Operations     Chennai       meena.reddy66@yahoo.com       Part time     -25000   23-09-2020                6.0                  100.0
66           67       Kavya Nair  42.0    male          Marketing        Pune        kavya.nair67@yahoo.com       Part-Time      73000   18-11-2025                2.0                   90.0
67           68     ravi sharma   55.0    male   Human Resources       Mumbai       ravi.sharma68@gmail.com        contract     -25000   29-01-2020                6.0                   95.0
68           69      Sneha Reddy  39.0       M                 IT        Pune      sneha.reddy69 @gmail.com        Contract      53000   18-01-2022                1.0                   75.0
69           70       Nisha Iyer  29.0    male                 IT   Bangalore        nisha.iyer70@yahoo.com       full time     118000   11-06-2026                0.0                  105.0
70           71       Ravi Patel  24.0     NaN                 it   Bangalore        ravi.patel71@gmail.com       Full-Time      58000   11-05-2023                1.0                   85.0
71           72   Karthik Joseph  40.0       F                 it    Hyderbad    karthik.joseph72@gmail.com             NaN      28000   13-10-2020                6.0                    NaN
72           73        Manoj Rao  40.0    Male              SALES     Chennai         manoj.rao73@yahoo.com       Part time     108000   23-10-2022                2.0                   90.0
73           74       Vijay Iyer  26.0       M                 HR    Hyderbad        vijay.iyer74@gmail.com       Full-Time      43000   09-09-2020                NaN                  105.0
74           75       Swetha Rao  39.0  Female   Human Resources         Pune        swetha.rao75@yahoo.com        contract      23000   06-08-2020                4.0                   95.0
75           76      Gokul Reddy   NaN       M          Marketing   Hyderabad       gokul.reddy76@gmail.com       Full-Time      33000   09-02-2024                1.0                   85.0
76           77     Meena Joseph   0.0   Male           Marketing  BANGALORE       meena.joseph77@gmail.com        Contract      63000   04-12-2022                6.0                   -5.0
77           78        Deepa Rao  26.0    male              SALES       Delhi         deepa.rao78@yahoo.com       Full-Time     113000   13-06-2018                2.0                   90.0
78           79     Gokul Joseph  22.0     NaN            Finance     Chennai    gokul.joseph79@company.com       Part time        NaN   08-01-2021                0.0                   95.0
79           80     Divya Joseph  48.0   Male          Operations  BANGALORE       divya.joseph80@gmail.com        Contract     118000   08-07-2023                3.5                   80.0
80         E081      Divya Singh  47.0    Male            finance     chennai       divya.singh81@yahoo.com       full time     -25000   23-07-2023                2.0                  100.0
81           82     Suresh Singh  28.0   Male    Human Resources     Hyderbad      suresh.singh82@gmail.com       Full-Time      78000   10-09-2023                4.0                   -5.0
82           83     Pooja Joseph  52.0       M          Marketing      Mumbai      pooja.joseph83@gmail.com        Contract     118000   16-12-2022                0.0                  105.0
83           84      Sneha Kumar  65.0    Male            finance        Pune       sneha.kumar84@gmail.com       Part time      53000   17-12-2025                NaN                   80.0
84           85   anitha sharma   50.0    male          Marketing  BANGALORE      anitha.sharma85@gmail.com       full time      33000   07-04-2025                0.0                  105.0
85           86       Anitha Rao   NaN       M              SALES    Chennai         anitha.rao86@gmail.com             NaN      38000   21-04-2022                2.0                   95.0
86           87      Kavya Singh  53.0     NaN              SALES        Pune                 invalid-email             NaN      58000   11-01-2018                3.0                  105.0
87           88        Nisha Rao  43.0  female   Human Resources      chennai       nisha.rao88@company.com             NaN      68000   10-03-2024                4.0                   90.0
88           89        Gokul Das  35.0   Male                  it  BANGALORE          gokul.das89@yahoo.com        contract      83000   28-06-2018                3.0                  105.0
89           90      Priya Patel  53.0     NaN                 HR  BANGALORE        priya.patel90@gmail.com       Full-Time     108000   21-09-2021                3.0                    NaN
90           91   Karthik Sharma  51.0  female                 HR     chennai  karthik.sharma91@company.com             NaN      58000   18-10-2021                6.0                    NaN
91           92         Ravi Rao  55.0       F          Marketing      Mumbai         ravi.rao92 @gmail.com        contract      23000   04-12-2024                2.0                    NaN
92           93     Sneha Sharma  49.0  female                 IT     Chennai      sneha.sharma93@yahoo.com             NaN  45000 INR   13-10-2025                1.0                   95.0
93           94      Pooja Singh  48.0       M              SALES     chennai     pooja.singh94@company.com       Part-Time      38000          NaN                3.0                   80.0
94           95       Swetha Das   NaN    male   Human Resources       Mumbai        swetha.das95@gmail.com       full time      93000   16-07-2024                5.0                   75.0
95           96       Manoj Iyer  55.0    male              SALES       Delhi        manoj.iyer96@yahoo.com        contract      43000   30-10-2018                NaN                   95.0
96           97       Manoj Iyer  33.0  female                 it      Mumbai        manoj.iyer97@gmail.com       Part time      78000   03-06-2023                5.0                   95.0
97           98         Arun Das  38.0     NaN              SALES     Chennai        arun.das98@company.com             NaN      18000   07-05-2024                5.0                   90.0
98           99     Swetha Singh  35.0  Female            Finance        Pune    swetha.singh99@company.com        contract     118000   18-02-2020                1.0                   95.0
99          100      Manoj Kumar  17.0  female          Marketing   Bangalore      manoj.kumar100@gmail.com        contract      73000   19-03-2026                NaN                   85.0
100         101      Vijay Patel  55.0    male            Finance        Pune    vijay.patel101@company.com             NaN      73000   15-12-2023                0.0                   95.0
101         102     ravi sharma   50.0  female            finance     chennai      ravi.sharma102@gmail.com       Full-Time      28000   31-07-2019                NaN                   75.0
102         103      Suresh Nair  28.0   Male               SALES        Pune    suresh.nair103@company.com             NaN      88000   18-02-2022                3.5                   80.0
103         104       Anitha Rao  22.0  Female              Sales     Chennai       anitha.rao104@yahoo.com        contract     113000   18-04-2024                0.0                   95.0

In [26]:
data.head(10)

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,03-07-2020,NaN,75.0
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,01-09-2023,6.0,NaN
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,27-01-2018,4.0,100.0
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,10-01-2022,0.0,-5.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,15-04-2021,2.0,75.0
5,6,Anitha Iyer,26.0,female,Human Resources,Pune,anitha.iyer6@yahoo.com,Part-Time,53000,18-02-2019,3.5,100.0
6,7,Vijay Iyer,25.0,M,Sales,Hyderbad,vijay.iyer7@gmail.com,full time,113000,13-02-2025,NaN,95.0
7,8,Nisha Reddy,41.0,male,it,Delhi,nisha.reddy8@gmail.com,Full-Time,23000,27-07-2020,4.0,100.0
8,9,Vijay Rao,46.0,F,Finance,Pune,vijay.rao9@gmail.com,contract,118000,23-02-2023,6.0,-5.0
9,10,Suresh Joseph,48.0,NaN,Finance,Mumbai,suresh.joseph10@yahoo.com,Full-Time,108000,24-06-2022,1.0,80.0

In [28]:
data.tail()

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
195,196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,27-03-2020,2.0,90.0
196,197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,22-12-2019,5.0,75.0
197,198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,16-03-2019,6.0,105.0
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,28-10-2019,3.5,95.0
199,200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,01-03-2025,NaN,80.0

In [29]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            200 non-null    str
 1   Employee_Name          200 non-null    str
 2   Age                    182 non-null    float64
 3   Gender                 177 non-null    str
 4   Department             197 non-null    str
 5   City                   200 non-null    str
 6   Email                  200 non-null    str
 7   Employment_Type        164 non-null    str
 8   Salary                 193 non-null    str
 9   Joining_Date           196 non-null    str
 10  Performance_Score      180 non-null    float64
 11  Attendance_Percentage  180 non-null    float64
dtypes: float64(3), str(9)
memory usage: 18.9 KB

In [31]:
data.sort_values(["Employee_Name","Age"])

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
84,85,anitha sharma,50.0,male,Marketing,BANGALORE,anitha.sharma85@gmail.com,full time,33000,07-04-2025,0.0,105.0
186,187,gokul joseph,35.0,Male,Finance,BANGALORE,gokul.joseph187@company.com,Part-Time,0,30-07-2018,4.0,75.0
169,170,gokul sharma,29.0,female,Human Resources,BANGALORE,gokul.sharma170@gmail.com,Part-Time,68000,16-03-2025,6.0,85.0
16,17,hari rao,28.0,F,IT,Delhi,hari.rao17@gmail.com,Part time,53000,09-07-2020,4.0,75.0
33,34,karthik das,29.0,F,Operations,Chennai,karthik.das34@yahoo.com,contract,23000,16-06-2021,4.0,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...
119,120,Vijay Patel,51.0,Female,Operations,Hyderbad,vijay.patel120@yahoo.com,NaN,53000,20-03-2019,5.0,90.0
100,101,Vijay Patel,55.0,male,Finance,Pune,vijay.patel101@company.com,NaN,73000,15-12-2023,0.0,95.0
36,37,Vijay Rao,43.0,Male,Sales,Chennai,vijay.rao37@gmail.com,Contract,63000,21-07-2020,5.0,80.0
8,9,Vijay Rao,46.0,F,Finance,Pune,vijay.rao9@gmail.com,contract,118000,23-02-2023,6.0,-5.0
190,191,Vijay Reddy,38.0,F,Marketing,Pune,vijay.reddy191@gmail.com,contract,103000,07-05-2021,0.0,100.0

In [35]:
data.isnull().sum()

Employee_ID               0
Employee_Name             0
Age                      18
Gender                   23
Department                3
City                      0
Email                     0
Employment_Type          36
Salary                    7
Joining_Date              4
Performance_Score        20
Attendance_Percentage    20
dtype: int64

In [36]:
df = data.dropna()

In [37]:
df.isnull().sum()

Employee_ID              0
Employee_Name            0
Age                      0
Gender                   0
Department               0
City                     0
Email                    0
Employment_Type          0
Salary                   0
Joining_Date             0
Performance_Score        0
Attendance_Percentage    0
dtype: int64

In [43]:
d = data.dropna(subset=["Age","Gender"])

In [44]:
d.isnull().sum()

Employee_ID               0
Employee_Name             0
Age                       0
Gender                    0
Department                3
City                      0
Email                     0
Employment_Type          28
Salary                    5
Joining_Date              3
Performance_Score        18
Attendance_Percentage    14
dtype: int64

In [45]:
data.fillna(0)

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,03-07-2020,0.0,75.0
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,01-09-2023,6.0,0.0
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,27-01-2018,4.0,100.0
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,10-01-2022,0.0,-5.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,15-04-2021,2.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,0,118000,27-03-2020,2.0,90.0
196,197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,22-12-2019,5.0,75.0
197,198,Arun Iyer,0.0,0,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,16-03-2019,6.0,105.0
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,28-10-2019,3.5,95.0
199,200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,01-03-2025,0.0,80.0

In [58]:
data = data["Gender"].fillna({"F":"Female"})

In [60]:
data

0      Female
1           F
2        male
3        Male
4           F
        ...
195      Male
196         M
197       NaN
198         M
199    female
Name: Gender, Length: 200, dtype: str

In [61]:
data

0      Female
1           F
2        male
3        Male
4           F
        ...
195      Male
196         M
197       NaN
198         M
199    female
Name: Gender, Length: 200, dtype: str

In [63]:
data

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,03-07-2020,NaN,75.0
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,01-09-2023,6.0,NaN
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,27-01-2018,4.0,100.0
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,10-01-2022,0.0,-5.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,15-04-2021,2.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,27-03-2020,2.0,90.0
196,197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,22-12-2019,5.0,75.0
197,198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,16-03-2019,6.0,105.0
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,28-10-2019,3.5,95.0
199,200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,01-03-2025,NaN,80.0

In [66]:
data["Gender"]=data["Gender"].fillna({"F":"Female","M":"Male"})

In [67]:
data

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,03-07-2020,NaN,75.0
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,01-09-2023,6.0,NaN
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,27-01-2018,4.0,100.0
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,10-01-2022,0.0,-5.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,15-04-2021,2.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,27-03-2020,2.0,90.0
196,197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,22-12-2019,5.0,75.0
197,198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,16-03-2019,6.0,105.0
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,28-10-2019,3.5,95.0
199,200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,01-03-2025,NaN,80.0

In [68]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [69]:
df

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,27-01-2018,4.0,100.0
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,10-01-2022,0.0,-5.0
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,15-04-2021,2.0,75.0
5,6,Anitha Iyer,26.0,female,Human Resources,Pune,anitha.iyer6@yahoo.com,Part-Time,53000,18-02-2019,3.5,100.0
7,8,Nisha Reddy,41.0,male,it,Delhi,nisha.reddy8@gmail.com,Full-Time,23000,27-07-2020,4.0,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
190,191,Vijay Reddy,38.0,F,Marketing,Pune,vijay.reddy191@gmail.com,contract,103000,07-05-2021,0.0,100.0
193,194,Suresh Nair,38.0,F,Sales,Chennai,suresh.nair194@company.com,Full-Time,38000,24-03-2019,6.0,90.0
194,195,Anitha Kumar,27.0,M,HR,BANGALORE,anitha.kumar195@company.com,Full-Time,83000,14-09-2021,6.0,85.0
196,197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,22-12-2019,5.0,75.0
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,28-10-2019,3.5,95.0

In [70]:
df.duplicated()

2      False
3      False
4      False
5      False
7      False
       ...
190    False
193    False
194    False
196    False
198    False
Length: 100, dtype: bool

In [71]:
df.duplicated().sum()

np.int64(0)

In [72]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            200 non-null    str
 1   Employee_Name          200 non-null    str
 2   Age                    182 non-null    float64
 3   Gender                 177 non-null    str
 4   Department             197 non-null    str
 5   City                   200 non-null    str
 6   Email                  200 non-null    str
 7   Employment_Type        164 non-null    str
 8   Salary                 193 non-null    str
 9   Joining_Date           196 non-null    str
 10  Performance_Score      180 non-null    float64
 11  Attendance_Percentage  180 non-null    float64
dtypes: float64(3), str(9)
memory usage: 18.9 KB

In [84]:
import numpy as np
data["Employee_ID"]=data["Employee_ID"].astype(np.int64)

ValueError: invalid literal for int() with base 10: 'E027'

In [86]:
print(data.to_string())

    Employee_ID    Employee_Name   Age  Gender         Department        City                         Email Employment_Type     Salary Joining_Date  Performance_Score  Attendance_Percentage
0             1      Sneha Kumar  38.0  Female            finance   Bangalore        sneha.kumar1@gmail.com       Part time      53000   03-07-2020                NaN                   75.0
1             2      Arun Sharma  34.0       F            finance     Chennai      arun.sharma2@company.com        contract      53000   01-09-2023                6.0                    NaN
2             3       Anitha Rao  17.0    male         Operations     chennai         anitha.rao3@gmail.com       Part-Time      58000   27-01-2018                4.0                  100.0
3             4     Sneha Sharma  45.0    Male          Marketing     Chennai       sneha.sharma4@yahoo.com        contract      33000   10-01-2022                0.0                   -5.0
4             5        Sneha Das  26.0       F         Operations     Chennai        sneha.das5@company.com        contract     103000   15-04-2021                2.0                   75.0
5             6      Anitha Iyer  26.0  female   Human Resources         Pune        anitha.iyer6@yahoo.com       Part-Time      53000   18-02-2019                3.5                  100.0
6             7       Vijay Iyer  25.0       M              Sales    Hyderbad         vijay.iyer7@gmail.com       full time     113000   13-02-2025                NaN                   95.0
7             8      Nisha Reddy  41.0    male                 it       Delhi        nisha.reddy8@gmail.com       Full-Time      23000   27-07-2020                4.0                  100.0
8             9        Vijay Rao  46.0       F            Finance        Pune          vijay.rao9@gmail.com        contract     118000   23-02-2023                6.0                   -5.0
9            10    Suresh Joseph  48.0     NaN            Finance      Mumbai     suresh.joseph10@yahoo.com       Full-Time     108000   24-06-2022                1.0                   80.0
10           11    Karthik Patel  48.0     NaN              SALES     chennai     karthik.patel11@yahoo.com       Part time     113000   18-09-2018                5.0                   -5.0
11           12      Arun Sharma  55.0   Male           Marketing   Bangalore       arun.sharma12@yahoo.com       Part-Time      58000   10-03-2025                0.0                   75.0
12           13      Suresh Nair  32.0       F            finance        Pune     suresh.nair13@company.com       Part-Time      98000   12-03-2019                3.5                   85.0
13           14       Nisha Nair  21.0  female                 HR     Chennai        nisha.nair14@yahoo.com             NaN     113000   20-08-2021                5.0                   90.0
14           15      Priya Reddy   0.0       M                 HR  BANGALORE      priya.reddy15@company.com       Part-Time      28000   17-12-2018                0.0                   -5.0
15           16       Divya Iyer  54.0    male              Sales    Hyderbad        divya.iyer16@gmail.com       full time     113000   30-09-2022                3.5                  105.0
16           17        hari rao   28.0       F                 IT       Delhi          hari.rao17@gmail.com       Part time      53000   09-07-2020                4.0                   75.0
17           18      Rahul Kumar  35.0       F            finance   Bangalore       rahul.kumar18@yahoo.com        Contract      28000   09-05-2018                0.0                   90.0
18           19      Nisha Patel   NaN       F                 it  BANGALORE        nisha.patel19@gmail.com       Full-Time     108000   21-04-2023                2.0                    NaN
19           20        Pooja Das  47.0   Male                  IT   Bangalore         pooja.das20@gmail.com        contract      88000   06-03-2026                3.5                   80.0
20           21     Anitha Reddy  33.0    male            Finance     chennai      anitha.reddy21@gmail.com       full time     103000   12-01-2023                4.0                   80.0
21           22       Manoj Nair  27.0       F                 HR     Chennai      manoj.nair22@company.com       Part-Time      23000   25-04-2025                NaN                  105.0
22           23      Deepa Reddy  46.0    male                 it     Chennai      deepa.reddy23 @yahoo.com             NaN      23000   06-11-2019                0.0                   95.0
23           24       Kavya Nair  52.0    Male                 IT      Mumbai        kavya.nair24@yahoo.com        contract      38000   17-02-2020                3.5                   75.0
24           25     Priya Joseph  51.0  Female            finance     Chennai      priya.joseph25@gmail.com             NaN      98000   16-12-2023                3.0                   80.0
25           26    Swetha Sharma  36.0    Male              SALES      Mumbai   swetha.sharma26@company.com       Part time      78000   07-05-2019                2.0                    NaN
26         E027     Gokul Joseph  54.0    male              Sales       Delhi      gokul.joseph27@gmail.com       full time      68000   04-12-2020                3.0                   95.0
27           28      Manoj Singh  25.0  Female                 HR     Chennai     manoj.singh28@company.com       Part time      18000   21-02-2023                4.0                   -5.0
28           29     Suresh Patel  43.0     NaN            Finance        Pune                 invalid-email             NaN      28000   27-09-2020                6.0                   95.0
29           30      Swetha Nair  21.0    male            Finance   Bangalore       swetha.nair30@yahoo.com       Full-Time        NaN   21-03-2024                2.0                   -5.0
30           31     Karthik Iyer  39.0    male              Sales       Delhi    karthik.iyer31@company.com       Part time  45000 INR   12-05-2020                0.0                   95.0
31           32     Priya Sharma  48.0    male            Finance       Delhi      priya.sharma32@gmail.com       Part-Time      58000   30-06-2018                0.0                   -5.0
32           33       Kavya Nair  21.0    Male            finance   Hyderabad      kavya.nair33@company.com             NaN      33000   05-11-2018                3.5                   -5.0
33           34     karthik das   29.0       F         Operations     Chennai       karthik.das34@yahoo.com        contract      23000   16-06-2021                4.0                   80.0
34           35       Pooja Nair  47.0       M            Finance      Mumbai        pooja.nair35@gmail.com       full time     113000   28-05-2026                1.0                   85.0
35           36         Ravi Das  36.0    Male                 it   Bangalore        ravi.das36@company.com             NaN      58000   15-10-2019                0.0                   90.0
36           37        Vijay Rao  43.0   Male               Sales     Chennai         vijay.rao37@gmail.com        Contract      63000   21-07-2020                5.0                   80.0
37           38     Suresh Singh   NaN  Female                 IT       Delhi    suresh.singh38@company.com        Contract      78000   15-08-2025                3.0                   95.0
38           39     Priya Sharma  65.0  Female                 it       Delhi    priya.sharma39@company.com       full time      83000   16-11-2021                4.0                   95.0
39           40        Priya Das  21.0   Male          Operations      Mumbai       priya.das40@company.com       Full-Time      98000   15-01-2024                3.5                  100.0
40           41       Sneha Iyer  53.0    male                 it       Delhi        sneha.iyer41@yahoo.com       Part time      63000   06-24-2025                3.0                   90.0
41           42        Kavya Das  32.0    Male            finance     chennai         kavya.das42@yahoo.com        Contract     113000   20-05-2024                5.0                   90.0
42           43     Kavya Joseph  65.0     NaN   Human Resources     Chennai       kavya.joseph43@yahoo.com        contract     118000   12-08-2021                4.0                   -5.0
43           44      Deepa Patel  26.0  Female         Operations     Chennai     deepa.patel44@company.com             NaN      63000   13-10-2023                4.0                   95.0
44           45     Anitha Reddy  30.0  Female              SALES  BANGALORE       anitha.reddy45@gmail.com       full time      18000   09-07-2018                NaN                   90.0
45           46         Ajay Rao  46.0   Male                  HR     Chennai       ajay.rao46 @company.com       Part-Time      53000   28-08-2019                3.0                   -5.0
46           47      Manoj Kumar   NaN  female   Human Resources    Hyderabad       manoj.kumar47@yahoo.com             NaN      53000          NaN                0.0                   -5.0
47           48       Kavya Nair  49.0       F          Marketing  BANGALORE         kavya.nair48@yahoo.com             NaN      43000   05-05-2026                5.0                   -5.0
48           49      Deepa Reddy  38.0    male              Sales        Pune     deepa.reddy49@company.com        Contract      88000   14-11-2018                3.5                   -5.0
49           50      Rahul Patel  30.0  Female              Sales   Hyderabad     rahul.patel50@company.com       full time      53000   18-04-2022                NaN                  100.0
50           51       nisha rao   47.0    Male              SALES     chennai         nisha.rao51@yahoo.com             NaN      23000   27-04-2020                NaN                  105.0
51           52       Arun Singh  40.0       F              SALES    Hyderbad      arun.singh52@company.com       full time      78000   13-09-2022                4.0                   95.0
52           53        Kavya Rao  22.0       M                NaN     chennai       kavya.rao53@company.com             NaN      78000   08-10-2021                0.0                   85.0
53         E054      Swetha Nair  22.0   Male                  HR     Chennai     swetha.nair54@company.com       Part-Time      78000   21-08-2024                0.0                   85.0
54           55       Priya Iyer  45.0   Male          Operations       Delhi        priya.iyer55@yahoo.com        Contract      68000   16-05-2020                NaN                   95.0
55           56        Rahul Rao  22.0  Female              Sales       Delhi         rahul.rao56@gmail.com             NaN          0   19-01-2024                1.0                   75.0
56           57     Anitha Reddy   NaN  Female   Human Resources    Hyderabad      anitha.reddy57@gmail.com       Part time     113000   17-09-2019                4.0                  105.0
57           58     Suresh Singh  31.0    male            Finance   Bangalore                 invalid-email       Full-Time     113000   23-10-2024                1.0                   95.0
58           59        Gokul Das  46.0  Female              Sales     Chennai         gokul.das59@gmail.com        contract     -25000   23-03-2020                5.0                   80.0
59           60      Gokul Kumar  43.0  female                 HR       Delhi     gokul.kumar60@company.com       Full-Time     103000   21-10-2022                NaN                  105.0
60           61        Sneha Das  44.0       M                 it   Hyderabad       sneha.das61@company.com        contract     118000   27-02-2023                6.0                   95.0
61           62      Swetha Nair  51.0  female          Marketing     Chennai     swetha.nair62@company.com             NaN  45000 INR   20-11-2022                4.0                   80.0
62           63       Suresh Rao  36.0    Male         Operations     chennai      suresh.rao63@company.com       full time      88000   23-05-2024                3.5                   85.0
63           64      Deepa Reddy  43.0    Male          Marketing     Chennai       deepa.reddy64@yahoo.com       Part time      58000   26-10-2021                4.0                   80.0
64           65       Anitha Das  52.0     NaN   Human Resources   BANGALORE       anitha.das65@company.com             NaN     103000   11-09-2020                1.0                   80.0
65           66      Meena Reddy  46.0     NaN         Operations     Chennai       meena.reddy66@yahoo.com       Part time     -25000   23-09-2020                6.0                  100.0
66           67       Kavya Nair  42.0    male          Marketing        Pune        kavya.nair67@yahoo.com       Part-Time      73000   18-11-2025                2.0                   90.0
67           68     ravi sharma   55.0    male   Human Resources       Mumbai       ravi.sharma68@gmail.com        contract     -25000   29-01-2020                6.0                   95.0
68           69      Sneha Reddy  39.0       M                 IT        Pune      sneha.reddy69 @gmail.com        Contract      53000   18-01-2022                1.0                   75.0
69           70       Nisha Iyer  29.0    male                 IT   Bangalore        nisha.iyer70@yahoo.com       full time     118000   11-06-2026                0.0                  105.0
70           71       Ravi Patel  24.0     NaN                 it   Bangalore        ravi.patel71@gmail.com       Full-Time      58000   11-05-2023                1.0                   85.0
71           72   Karthik Joseph  40.0       F                 it    Hyderbad    karthik.joseph72@gmail.com             NaN      28000   13-10-2020                6.0                    NaN
72           73        Manoj Rao  40.0    Male              SALES     Chennai         manoj.rao73@yahoo.com       Part time     108000   23-10-2022                2.0                   90.0
73           74       Vijay Iyer  26.0       M                 HR    Hyderbad        vijay.iyer74@gmail.com       Full-Time      43000   09-09-2020                NaN                  105.0
74           75       Swetha Rao  39.0  Female   Human Resources         Pune        swetha.rao75@yahoo.com        contract      23000   06-08-2020                4.0                   95.0
75           76      Gokul Reddy   NaN       M          Marketing   Hyderabad       gokul.reddy76@gmail.com       Full-Time      33000   09-02-2024                1.0                   85.0
76           77     Meena Joseph   0.0   Male           Marketing  BANGALORE       meena.joseph77@gmail.com        Contract      63000   04-12-2022                6.0                   -5.0
77           78        Deepa Rao  26.0    male              SALES       Delhi         deepa.rao78@yahoo.com       Full-Time     113000   13-06-2018                2.0                   90.0
78           79     Gokul Joseph  22.0     NaN            Finance     Chennai    gokul.joseph79@company.com       Part time        NaN   08-01-2021                0.0                   95.0
79           80     Divya Joseph  48.0   Male          Operations  BANGALORE       divya.joseph80@gmail.com        Contract     118000   08-07-2023                3.5                   80.0
80         E081      Divya Singh  47.0    Male            finance     chennai       divya.singh81@yahoo.com       full time     -25000   23-07-2023                2.0                  100.0
81           82     Suresh Singh  28.0   Male    Human Resources     Hyderbad      suresh.singh82@gmail.com       Full-Time      78000   10-09-2023                4.0                   -5.0
82           83     Pooja Joseph  52.0       M          Marketing      Mumbai      pooja.joseph83@gmail.com        Contract     118000   16-12-2022                0.0                  105.0
83           84      Sneha Kumar  65.0    Male            finance        Pune       sneha.kumar84@gmail.com       Part time      53000   17-12-2025                NaN                   80.0
84           85   anitha sharma   50.0    male          Marketing  BANGALORE      anitha.sharma85@gmail.com       full time      33000   07-04-2025                0.0                  105.0
85           86       Anitha Rao   NaN       M              SALES    Chennai         anitha.rao86@gmail.com             NaN      38000   21-04-2022                2.0                   95.0
86           87      Kavya Singh  53.0     NaN              SALES        Pune                 invalid-email             NaN      58000   11-01-2018                3.0                  105.0
87           88        Nisha Rao  43.0  female   Human Resources      chennai       nisha.rao88@company.com             NaN      68000   10-03-2024                4.0                   90.0
88           89        Gokul Das  35.0   Male                  it  BANGALORE          gokul.das89@yahoo.com        contract      83000   28-06-2018                3.0                  105.0
89           90      Priya Patel  53.0     NaN                 HR  BANGALORE        priya.patel90@gmail.com       Full-Time     108000   21-09-2021                3.0                    NaN
90           91   Karthik Sharma  51.0  female                 HR     chennai  karthik.sharma91@company.com             NaN      58000   18-10-2021                6.0                    NaN
91           92         Ravi Rao  55.0       F          Marketing      Mumbai         ravi.rao92 @gmail.com        contract      23000   04-12-2024                2.0                    NaN
92           93     Sneha Sharma  49.0  female                 IT     Chennai      sneha.sharma93@yahoo.com             NaN  45000 INR   13-10-2025                1.0                   95.0
93           94      Pooja Singh  48.0       M              SALES     chennai     pooja.singh94@company.com       Part-Time      38000          NaN                3.0                   80.0
94           95       Swetha Das   NaN    male   Human Resources       Mumbai        swetha.das95@gmail.com       full time      93000   16-07-2024                5.0                   75.0
95           96       Manoj Iyer  55.0    male              SALES       Delhi        manoj.iyer96@yahoo.com        contract      43000   30-10-2018                NaN                   95.0
96           97       Manoj Iyer  33.0  female                 it      Mumbai        manoj.iyer97@gmail.com       Part time      78000   03-06-2023                5.0                   95.0
97           98         Arun Das  38.0     NaN              SALES     Chennai        arun.das98@company.com             NaN      18000   07-05-2024                5.0                   90.0
98           99     Swetha Singh  35.0  Female            Finance        Pune    swetha.singh99@company.com        contract     118000   18-02-2020                1.0                   95.0
99          100      Manoj Kumar  17.0  female          Marketing   Bangalore      manoj.kumar100@gmail.com        contract      73000   19-03-2026                NaN                   85.0
100         101      Vijay Patel  55.0    male            Finance        Pune    vijay.patel101@company.com             NaN      73000   15-12-2023                0.0                   95.0
101         102     ravi sharma   50.0  female            finance     chennai      ravi.sharma102@gmail.com       Full-Time      28000   31-07-2019                NaN                   75.0
102         103      Suresh Nair  28.0   Male               SALES        Pune    suresh.nair103@company.com             NaN      88000   18-02-2022                3.5                   80.0
103         104       Anitha Rao  22.0  Female              Sales     Chennai       anitha.rao104@yahoo.com        contract     113000   18-04-2024                0.0                   95.0

In [87]:
print(data.dtype())

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [88]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            200 non-null    str
 1   Employee_Name          200 non-null    str
 2   Age                    182 non-null    float64
 3   Gender                 177 non-null    str
 4   Department             197 non-null    str
 5   City                   200 non-null    str
 6   Email                  200 non-null    str
 7   Employment_Type        164 non-null    str
 8   Salary                 193 non-null    str
 9   Joining_Date           196 non-null    str
 10  Performance_Score      180 non-null    float64
 11  Attendance_Percentage  180 non-null    float64
dtypes: float64(3), str(9)
memory usage: 18.9 KB

In [89]:
data["City"].str.title()

0       Bangalore
1         Chennai
2         Chennai
3         Chennai
4         Chennai
          ...
195         Delhi
196       Chennai
197          Pune
198    Bangalore
199       Chennai
Name: City, Length: 200, dtype: str

In [92]:
data["Gender"].str.replace("F","Female")

0      Femaleemale
1           Female
2             male
3             Male
4           Female
          ...
195           Male
196              M
197            NaN
198              M
199         female
Name: Gender, Length: 200, dtype: str

In [102]:
data["Year"] = data["Joining_Date"].dt.year

In [95]:
data["Joining_Date"]=pd.to_datetime(data["Joining_Date"],format="mixed")

In [103]:
data["Year"]

0      2020.0
1      2023.0
2      2018.0
3      2022.0
4      2021.0
        ...
195    2020.0
196    2019.0
197    2019.0
198    2019.0
199    2025.0
Name: Year, Length: 200, dtype: float64

In [101]:
data.columns

Index(['Employee_ID', 'Employee_Name', 'Age', 'Gender', 'Department', 'City',
       'Email', 'Employment_Type', 'Salary', 'Joining_Date',
       'Performance_Score', 'Attendance_Percentage', 'Year'],
      dtype='str')

In [104]:
data["day_name"] =data["Joining_Date"].dt.day_name()

In [105]:
data

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage,Year,day_name
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,2020-03-07,NaN,75.0,2020.0,Saturday
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,2023-01-09,6.0,NaN,2023.0,Monday
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,2018-01-27,4.0,100.0,2018.0,Saturday
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,2022-10-01,0.0,-5.0,2022.0,Saturday
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,2021-04-15,2.0,75.0,2021.0,Thursday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,2020-03-27,2.0,90.0,2020.0,Friday
196,197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,2019-12-22,5.0,75.0,2019.0,Sunday
197,198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,2019-03-16,6.0,105.0,2019.0,Saturday
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,2019-10-28,3.5,95.0,2019.0,Monday
199,200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,2025-01-03,NaN,80.0,2025.0,Friday

In [110]:
def categorize(age):
    return 'Senior' if age > 30 else 'Junior'
 
data['Category'] = data['Age'].apply(lambda a:"High" if a>40 else "Low")
# or with a lambda:
#df['Category'] = df['Age'].apply(lambda x: 'Senior' if x > 30 else 'Junior')

In [111]:
data

,Employee_ID,Employee_Name,Age,Gender,Department,City,Email,Employment_Type,Salary,Joining_Date,Performance_Score,Attendance_Percentage,Year,day_name,Category
0,1,Sneha Kumar,38.0,Female,finance,Bangalore,sneha.kumar1@gmail.com,Part time,53000,2020-03-07,NaN,75.0,2020.0,Saturday,Low
1,2,Arun Sharma,34.0,F,finance,Chennai,arun.sharma2@company.com,contract,53000,2023-01-09,6.0,NaN,2023.0,Monday,Low
2,3,Anitha Rao,17.0,male,Operations,chennai,anitha.rao3@gmail.com,Part-Time,58000,2018-01-27,4.0,100.0,2018.0,Saturday,Low
3,4,Sneha Sharma,45.0,Male,Marketing,Chennai,sneha.sharma4@yahoo.com,contract,33000,2022-10-01,0.0,-5.0,2022.0,Saturday,High
4,5,Sneha Das,26.0,F,Operations,Chennai,sneha.das5@company.com,contract,103000,2021-04-15,2.0,75.0,2021.0,Thursday,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,Kavya Rao,51.0,Male,Marketing,Delhi,kavya.rao196@yahoo.com,NaN,118000,2020-03-27,2.0,90.0,2020.0,Friday,High
196,197,Nisha Kumar,32.0,M,Human Resources,chennai,nisha.kumar197@gmail.com,contract,83000,2019-12-22,5.0,75.0,2019.0,Sunday,Low
197,198,Arun Iyer,0.0,NaN,Human Resources,Pune,arun.iyer198@yahoo.com,Part-Time,113000,2019-03-16,6.0,105.0,2019.0,Saturday,Low
198,199,Suresh Reddy,28.0,M,Marketing,BANGALORE,suresh.reddy199@company.com,Full-Time,68000,2019-10-28,3.5,95.0,2019.0,Monday,Low
199,200,Gokul Reddy,32.0,female,finance,chennai,gokul.reddy200@yahoo.com,Full-Time,113000,2025-01-03,NaN,80.0,2025.0,Friday,Low